// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"sync"
)

// Ensure, that RelayStoreMock does implement RelayStore.
// If this is not the case, regenerate this file with moq.
var _ RelayStore = &RelayStoreMock{}

// RelayStoreMock is a mock implementation of RelayStore.
//
//     func TestSomethingThatUsesRelayStore(t *testing.T) {
//
//         // make and configure a mocked RelayStore
//         mockedRelayStore := &RelayStoreMock{
//             DeleteFunc: func(relayID uint64) error {
// 	               panic("mock out the Delete method")
//             },
//             ExpireResetFunc: func(relayID uint64) error {
// 	               panic("mock out the ExpireReset method")
//             },
//             GetFunc: func(relayID uint64) (*RelayStoreData, error) {
// 	               panic("mock out the Get method")
//             },
//             GetAllFunc: func() ([]*RelayStoreData, error) {
// 	               panic("mock out the GetAll method")
//             },
//             SetFunc: func(in1 RelayStoreData) error {
// 	               panic("mock out the Set method")
//             },
//         }
//
//         // use mockedRelayStore in code that requires RelayStore
//         // and then make assertions.
//
//     }
type RelayStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(relayID uint64) error

	// ExpireResetFunc mocks the ExpireReset method.
	ExpireResetFunc func(relayID uint64) error

	// GetFunc mocks the Get method.
	GetFunc func(relayID uint64) (*RelayStoreData, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() ([]*RelayStoreData, error)

	// SetFunc mocks the Set method.
	SetFunc func(in1 RelayStoreData) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// RelayID is the relayID argument value.
			RelayID uint64
		}
		// ExpireReset holds details about calls to the ExpireReset method.
		ExpireReset []struct {
			// RelayID is the relayID argument value.
			RelayID uint64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// RelayID is the relayID argument value.
			RelayID uint64
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// In1 is the in1 argument value.
			In1 RelayStoreData
		}
	}
	lockDelete      sync.RWMutex
	lockExpireReset sync.RWMutex
	lockGet         sync.RWMutex
	lockGetAll      sync.RWMutex
	lockSet         sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *RelayStoreMock) Delete(relayID uint64) error {
	if mock.DeleteFunc == nil {
		panic("RelayStoreMock.DeleteFunc: method is nil but RelayStore.Delete was just called")
	}
	callInfo := struct {
		RelayID uint64
	}{
		RelayID: relayID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(relayID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedRelayStore.DeleteCalls())
func (mock *RelayStoreMock) DeleteCalls() []struct {
	RelayID uint64
} {
	var calls []struct {
		RelayID uint64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ExpireReset calls ExpireResetFunc.
func (mock *RelayStoreMock) ExpireReset(relayID uint64) error {
	if mock.ExpireResetFunc == nil {
		panic("RelayStoreMock.ExpireResetFunc: method is nil but RelayStore.ExpireReset was just called")
	}
	callInfo := struct {
		RelayID uint64
	}{
		RelayID: relayID,
	}
	mock.lockExpireReset.Lock()
	mock.calls.ExpireReset = append(mock.calls.ExpireReset, callInfo)
	mock.lockExpireReset.Unlock()
	return mock.ExpireResetFunc(relayID)
}

// ExpireResetCalls gets all the calls that were made to ExpireReset.
// Check the length with:
//     len(mockedRelayStore.ExpireResetCalls())
func (mock *RelayStoreMock) ExpireResetCalls() []struct {
	RelayID uint64
} {
	var calls []struct {
		RelayID uint64
	}
	mock.lockExpireReset.RLock()
	calls = mock.calls.ExpireReset
	mock.lockExpireReset.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RelayStoreMock) Get(relayID uint64) (*RelayStoreData, error) {
	if mock.GetFunc == nil {
		panic("RelayStoreMock.GetFunc: method is nil but RelayStore.Get was just called")
	}
	callInfo := struct {
		RelayID uint64
	}{
		RelayID: relayID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(relayID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedRelayStore.GetCalls())
func (mock *RelayStoreMock) GetCalls() []struct {
	RelayID uint64
} {
	var calls []struct {
		RelayID uint64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *RelayStoreMock) GetAll() ([]*RelayStoreData, error) {
	if mock.GetAllFunc == nil {
		panic("RelayStoreMock.GetAllFunc: method is nil but RelayStore.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedRelayStore.GetAllCalls())
func (mock *RelayStoreMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *RelayStoreMock) Set(in1 RelayStoreData) error {
	if mock.SetFunc == nil {
		panic("RelayStoreMock.SetFunc: method is nil but RelayStore.Set was just called")
	}
	callInfo := struct {
		In1 RelayStoreData
	}{
		In1: in1,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(in1)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//     len(mockedRelayStore.SetCalls())
func (mock *RelayStoreMock) SetCalls() []struct {
	In1 RelayStoreData
} {
	var calls []struct {
		In1 RelayStoreData
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
