# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_portable
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_portable)
  next_config = debug_portable
  enet_config = debug_portable
  sodium_config = debug_portable
  client_config = debug_portable
  server_config = debug_portable
endif
ifeq ($(config),debug_x64)
  next_config = debug_x64
  enet_config = debug_x64
  sodium_config = debug_x64
  client_config = debug_x64
  server_config = debug_x64
endif
ifeq ($(config),release_portable)
  next_config = release_portable
  enet_config = release_portable
  sodium_config = release_portable
  client_config = release_portable
  server_config = release_portable
endif
ifeq ($(config),release_x64)
  next_config = release_x64
  enet_config = release_x64
  sodium_config = release_x64
  client_config = release_x64
  server_config = release_x64
endif

PROJECTS := next enet sodium client server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

next: sodium
ifneq (,$(next_config))
	@echo "==== Building next ($(next_config)) ===="
	@${MAKE} --no-print-directory -C . -f next.make config=$(next_config)
endif

enet: next
ifneq (,$(enet_config))
	@echo "==== Building enet ($(enet_config)) ===="
	@${MAKE} --no-print-directory -C . -f enet.make config=$(enet_config)
endif

sodium:
ifneq (,$(sodium_config))
	@echo "==== Building sodium ($(sodium_config)) ===="
	@${MAKE} --no-print-directory -C . -f sodium.make config=$(sodium_config)
endif

client: enet next sodium
ifneq (,$(client_config))
	@echo "==== Building client ($(client_config)) ===="
	@${MAKE} --no-print-directory -C . -f client.make config=$(client_config)
endif

server: enet next sodium
ifneq (,$(server_config))
	@echo "==== Building server ($(server_config)) ===="
	@${MAKE} --no-print-directory -C . -f server.make config=$(server_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f next.make clean
	@${MAKE} --no-print-directory -C . -f enet.make clean
	@${MAKE} --no-print-directory -C . -f sodium.make clean
	@${MAKE} --no-print-directory -C . -f client.make clean
	@${MAKE} --no-print-directory -C . -f server.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_portable"
	@echo "  debug_x64"
	@echo "  release_portable"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   next"
	@echo "   enet"
	@echo "   sodium"
	@echo "   client"
	@echo "   server"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"