MAKEFILE_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

include $(MAKEFILE_DIR)/Makefile.common

############
### Vars ###
############

EXE										:= relay.test

SRC_OBJ_FILES					:= $(patsubst $(SRC)/%.cpp, $(OBJ)/$(SRC)/%.test.o, $(SRC_FILES))
SRC_DEP_FILES					:= $(patsubst $(SRC)/%.cpp, $(OBJ)/$(SRC)/%.test.d, $(SRC_FILES))

ifndef LOG_LEVEL
LOG_LEVEL             := 0
endif

DEF_FLAGS							:= -DTEST_BUILD -DRELAY_LOG_LEVEL=$(LOG_LEVEL)

ifeq ($(LOG_ALL),true)
DEF_FLAGS 						:= $(DEF_FLAGS) -DLOG_ALL
endif

COMMON_FLAGS 					:= $(CXX) $(CXX_FLAGS) $(CXX_DBG_FLAGS)
COMMON_COMPILE_FLAGS 	:= $(COMMON_FLAGS) -c $(DEF_FLAGS)

################
### Targets  ###
################

.PHONY: all
all:  $(BIN)/$(EXE)

.PHONY: run
run: $(BIN)/$(EXE)
	@$< $(TESTS)

.PHONY: clean
clean:
	@rm -f $(BIN)/$(EXE) $(SRC_OBJ_FILES) $(SRC_DEP_FILES) $(GCH)

##############
### Builds ###
##############

# precompiled header
$(GCH): $(PCH) Makefile
	$(COMMON_COMPILE_FLAGS) -o $@ $(INCLUDE_DIRS) -x c++-header $<

# all object files
$(OBJ)/%.test.o: %.cpp $(GCH)
	$(COMMON_COMPILE_FLAGS) -o $@ $(INCLUDE_DIRS) -MMD -MP $<

# the executable
$(BIN)/$(EXE): $(SRC_OBJ_FILES)
	$(COMMON_FLAGS) -o $@ $^ $(LIBRARIES)

-include $(SRC_DEP_FILES)
