#!/bin/bash
set -e
set -o pipefail

if [ -z "$NEXT_HOME" ]; then
	export NEXT_HOME="$( cd "$(dirname "$0")" ; pwd -P )"
fi

source="scripts"

unset -v latest
for file in $source/*; do
	[[ $file -nt $latest ]] && latest=$file
done

tool_path="scripts/make-release"
if [ ! -f $tool_path ] || [ $latest -nt $tool_path ]; then
	go build -o $tool_path $source/*.go
fi
$tool_path "$@"

