#!/bin/bash

unset -v latest
for file in tools/next/*.go; do
	[[ $file -nt $latest ]] && latest=$file
done

if [ ! -f ./dist/next ] || [ $latest -nt ./dist/next ]; then
	mkdir -p ./dist
	go build -o ./dist/next tools/next/*.go || { echo 'failed to build next.go' ; exit 1; }
fi

./dist/next "$@"
