#!/bin/bash

unset -v latest
for file in scripts/next/*.go; do
	[[ $file -nt $latest ]] && latest=$file
done

if [ ! -f ./dist/next ] || [ $latest -nt ./dist/next ]; then
	go build -o ./dist/next scripts/next/*.go
fi

./dist/next "$@"
