// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2_init/v2_init.proto

package com.networknext.api.v2_init;

public final class V2Init {
  private V2Init() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025v2_init/v2_init.proto\022\007v2_init\032-data_f" +
      "orward_common/data_forward_common.proto2" +
      "o\n\020V2InitUdpService\022[\n\004Init\022\'.data_forwa" +
      "rd_common.DataForwardRequest\032(.data_forw" +
      "ard_common.DataForwardResponse\"\000B&\n\033com." +
      "networknext.api.v2_initZ\007v2_initb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor(),
        }, assigner);
    com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
