
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS route_shaders CASCADE;
DROP TABLE IF EXISTS datacenters CASCADE;
DROP TABLE IF EXISTS datacenter_maps CASCADE;
DROP TABLE IF EXISTS relays CASCADE;
