#ifndef CONFIG_HPP
#define CONFIG_HPP

// Legacy, use bools instead, eventually delete and replace these
#define RELAY_OK 0
#define RELAY_ERROR -1

#define RELAY_MTU 1300

#define RELAY_HEADER_BYTES 35

#define RELAY_ADDRESS_BUFFER_SAFETY 32
#define RELAY_PING_PACKET_BYTES 1 + 8 + net::Address::ByteSize // identifier, seq num, ..., is v3

#define RELAY_REPLAY_PROTECTION_BUFFER_SIZE 256UL

#define RELAY_BANDWIDTH_LIMITER_INTERVAL 1.0

#define RELAY_DIRECTION_CLIENT_TO_SERVER 0
#define RELAY_DIRECTION_SERVER_TO_CLIENT 1

#define RELAY_ROUTE_REQUEST_PACKET 1
#define RELAY_ROUTE_RESPONSE_PACKET 2
#define RELAY_CLIENT_TO_SERVER_PACKET 3
#define RELAY_SERVER_TO_CLIENT_PACKET 4
#define RELAY_SESSION_PING_PACKET 11
#define RELAY_SESSION_PONG_PACKET 12
#define RELAY_CONTINUE_REQUEST_PACKET 13
#define RELAY_CONTINUE_RESPONSE_PACKET 14
#define RELAY_NEAR_PING_PACKET 73
#define RELAY_NEAR_PONG_PACKET 74

#define RELAY_PING_HISTORY_ENTRY_COUNT 256

#define RELAY_PING_TIME 0.1
#define RELAY_PING_TIME_MILLIS 100

#define RELAY_STATS_WINDOW 100
#define RELAY_PING_SAFETY 10

#define RELAY_MAX_PACKET_BYTES 1500

#define RELAY_PUBLIC_KEY_BYTES 32UL
#define RELAY_PRIVATE_KEY_BYTES 32UL

#define RELAY_MAX_ADDRESS_STRING_LENGTH 256

#define MAX_RELAYS 1024

#define RELAY_TOKEN_BYTES 32
#define RESPONSE_MAX_BYTES 1024 * 1024

#define NEAR_PING_PACKET 73
#define NEAR_PONG_PACKET 74
#define RELAY_PING_PACKET 75
#define RELAY_PONG_PACKET 76

#define INVALID_SEQUENCE_NUMBER 0xFFFFFFFFFFFFFFFFULL

/* This will prevent GCC from optimizing out useless function calls, for benchmarking */
#ifdef BENCH_BUILD
#define GCC_NO_OPT_OUT asm("")
#else
#define GCC_NO_OPT_OUT
#endif

#endif