// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_ingress_data/server_ingress_data.proto

package com.networknext.api.server_ingress_data;

public final class ServerIngressData {
  private ServerIngressData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerIngressServerDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server_ingress_data.ServerIngressServerData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes serverRoutePublicKey = 1;</code>
     */
    com.google.protobuf.ByteString getServerRoutePublicKey();

    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    boolean hasDatacenterId();
    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    com.networknext.api.id.Id.EntityId getDatacenterId();
    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    com.networknext.api.id.Id.EntityIdOrBuilder getDatacenterIdOrBuilder();

    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    boolean hasServerPrivateIpAddress();
    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    com.networknext.api.address.AddressOuterClass.Address getServerPrivateIpAddress();
    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    com.networknext.api.address.AddressOuterClass.AddressOrBuilder getServerPrivateIpAddressOrBuilder();

    /**
     * <code>int32 versionMajor = 4;</code>
     */
    int getVersionMajor();

    /**
     * <code>int32 versionMinor = 5;</code>
     */
    int getVersionMinor();

    /**
     * <code>int32 versionPatch = 6;</code>
     */
    int getVersionPatch();

    /**
     * <code>bool datacenterEnabled = 7;</code>
     */
    boolean getDatacenterEnabled();

    /**
     * <code>string datacenterName = 8;</code>
     */
    java.lang.String getDatacenterName();
    /**
     * <code>string datacenterName = 8;</code>
     */
    com.google.protobuf.ByteString
        getDatacenterNameBytes();
  }
  /**
   * Protobuf type {@code server_ingress_data.ServerIngressServerData}
   */
  public  static final class ServerIngressServerData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server_ingress_data.ServerIngressServerData)
      ServerIngressServerDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerIngressServerData.newBuilder() to construct.
    private ServerIngressServerData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerIngressServerData() {
      serverRoutePublicKey_ = com.google.protobuf.ByteString.EMPTY;
      versionMajor_ = 0;
      versionMinor_ = 0;
      versionPatch_ = 0;
      datacenterEnabled_ = false;
      datacenterName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerIngressServerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              serverRoutePublicKey_ = input.readBytes();
              break;
            }
            case 18: {
              com.networknext.api.id.Id.EntityId.Builder subBuilder = null;
              if (datacenterId_ != null) {
                subBuilder = datacenterId_.toBuilder();
              }
              datacenterId_ = input.readMessage(com.networknext.api.id.Id.EntityId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(datacenterId_);
                datacenterId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.networknext.api.address.AddressOuterClass.Address.Builder subBuilder = null;
              if (serverPrivateIpAddress_ != null) {
                subBuilder = serverPrivateIpAddress_.toBuilder();
              }
              serverPrivateIpAddress_ = input.readMessage(com.networknext.api.address.AddressOuterClass.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverPrivateIpAddress_);
                serverPrivateIpAddress_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              versionMajor_ = input.readInt32();
              break;
            }
            case 40: {

              versionMinor_ = input.readInt32();
              break;
            }
            case 48: {

              versionPatch_ = input.readInt32();
              break;
            }
            case 56: {

              datacenterEnabled_ = input.readBool();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              datacenterName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.server_ingress_data.ServerIngressData.internal_static_server_ingress_data_ServerIngressServerData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.server_ingress_data.ServerIngressData.internal_static_server_ingress_data_ServerIngressServerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.class, com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.Builder.class);
    }

    public static final int SERVERROUTEPUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString serverRoutePublicKey_;
    /**
     * <code>bytes serverRoutePublicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getServerRoutePublicKey() {
      return serverRoutePublicKey_;
    }

    public static final int DATACENTERID_FIELD_NUMBER = 2;
    private com.networknext.api.id.Id.EntityId datacenterId_;
    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    public boolean hasDatacenterId() {
      return datacenterId_ != null;
    }
    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    public com.networknext.api.id.Id.EntityId getDatacenterId() {
      return datacenterId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : datacenterId_;
    }
    /**
     * <code>.id.EntityId datacenterId = 2;</code>
     */
    public com.networknext.api.id.Id.EntityIdOrBuilder getDatacenterIdOrBuilder() {
      return getDatacenterId();
    }

    public static final int SERVERPRIVATEIPADDRESS_FIELD_NUMBER = 3;
    private com.networknext.api.address.AddressOuterClass.Address serverPrivateIpAddress_;
    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    public boolean hasServerPrivateIpAddress() {
      return serverPrivateIpAddress_ != null;
    }
    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    public com.networknext.api.address.AddressOuterClass.Address getServerPrivateIpAddress() {
      return serverPrivateIpAddress_ == null ? com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : serverPrivateIpAddress_;
    }
    /**
     * <code>.address.Address serverPrivateIpAddress = 3;</code>
     */
    public com.networknext.api.address.AddressOuterClass.AddressOrBuilder getServerPrivateIpAddressOrBuilder() {
      return getServerPrivateIpAddress();
    }

    public static final int VERSIONMAJOR_FIELD_NUMBER = 4;
    private int versionMajor_;
    /**
     * <code>int32 versionMajor = 4;</code>
     */
    public int getVersionMajor() {
      return versionMajor_;
    }

    public static final int VERSIONMINOR_FIELD_NUMBER = 5;
    private int versionMinor_;
    /**
     * <code>int32 versionMinor = 5;</code>
     */
    public int getVersionMinor() {
      return versionMinor_;
    }

    public static final int VERSIONPATCH_FIELD_NUMBER = 6;
    private int versionPatch_;
    /**
     * <code>int32 versionPatch = 6;</code>
     */
    public int getVersionPatch() {
      return versionPatch_;
    }

    public static final int DATACENTERENABLED_FIELD_NUMBER = 7;
    private boolean datacenterEnabled_;
    /**
     * <code>bool datacenterEnabled = 7;</code>
     */
    public boolean getDatacenterEnabled() {
      return datacenterEnabled_;
    }

    public static final int DATACENTERNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object datacenterName_;
    /**
     * <code>string datacenterName = 8;</code>
     */
    public java.lang.String getDatacenterName() {
      java.lang.Object ref = datacenterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datacenterName_ = s;
        return s;
      }
    }
    /**
     * <code>string datacenterName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDatacenterNameBytes() {
      java.lang.Object ref = datacenterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datacenterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!serverRoutePublicKey_.isEmpty()) {
        output.writeBytes(1, serverRoutePublicKey_);
      }
      if (datacenterId_ != null) {
        output.writeMessage(2, getDatacenterId());
      }
      if (serverPrivateIpAddress_ != null) {
        output.writeMessage(3, getServerPrivateIpAddress());
      }
      if (versionMajor_ != 0) {
        output.writeInt32(4, versionMajor_);
      }
      if (versionMinor_ != 0) {
        output.writeInt32(5, versionMinor_);
      }
      if (versionPatch_ != 0) {
        output.writeInt32(6, versionPatch_);
      }
      if (datacenterEnabled_ != false) {
        output.writeBool(7, datacenterEnabled_);
      }
      if (!getDatacenterNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, datacenterName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!serverRoutePublicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, serverRoutePublicKey_);
      }
      if (datacenterId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDatacenterId());
      }
      if (serverPrivateIpAddress_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getServerPrivateIpAddress());
      }
      if (versionMajor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, versionMajor_);
      }
      if (versionMinor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, versionMinor_);
      }
      if (versionPatch_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, versionPatch_);
      }
      if (datacenterEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, datacenterEnabled_);
      }
      if (!getDatacenterNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, datacenterName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData)) {
        return super.equals(obj);
      }
      com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData other = (com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData) obj;

      boolean result = true;
      result = result && getServerRoutePublicKey()
          .equals(other.getServerRoutePublicKey());
      result = result && (hasDatacenterId() == other.hasDatacenterId());
      if (hasDatacenterId()) {
        result = result && getDatacenterId()
            .equals(other.getDatacenterId());
      }
      result = result && (hasServerPrivateIpAddress() == other.hasServerPrivateIpAddress());
      if (hasServerPrivateIpAddress()) {
        result = result && getServerPrivateIpAddress()
            .equals(other.getServerPrivateIpAddress());
      }
      result = result && (getVersionMajor()
          == other.getVersionMajor());
      result = result && (getVersionMinor()
          == other.getVersionMinor());
      result = result && (getVersionPatch()
          == other.getVersionPatch());
      result = result && (getDatacenterEnabled()
          == other.getDatacenterEnabled());
      result = result && getDatacenterName()
          .equals(other.getDatacenterName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERROUTEPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getServerRoutePublicKey().hashCode();
      if (hasDatacenterId()) {
        hash = (37 * hash) + DATACENTERID_FIELD_NUMBER;
        hash = (53 * hash) + getDatacenterId().hashCode();
      }
      if (hasServerPrivateIpAddress()) {
        hash = (37 * hash) + SERVERPRIVATEIPADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getServerPrivateIpAddress().hashCode();
      }
      hash = (37 * hash) + VERSIONMAJOR_FIELD_NUMBER;
      hash = (53 * hash) + getVersionMajor();
      hash = (37 * hash) + VERSIONMINOR_FIELD_NUMBER;
      hash = (53 * hash) + getVersionMinor();
      hash = (37 * hash) + VERSIONPATCH_FIELD_NUMBER;
      hash = (53 * hash) + getVersionPatch();
      hash = (37 * hash) + DATACENTERENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDatacenterEnabled());
      hash = (37 * hash) + DATACENTERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDatacenterName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server_ingress_data.ServerIngressServerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server_ingress_data.ServerIngressServerData)
        com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.server_ingress_data.ServerIngressData.internal_static_server_ingress_data_ServerIngressServerData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.server_ingress_data.ServerIngressData.internal_static_server_ingress_data_ServerIngressServerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.class, com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.Builder.class);
      }

      // Construct using com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverRoutePublicKey_ = com.google.protobuf.ByteString.EMPTY;

        if (datacenterIdBuilder_ == null) {
          datacenterId_ = null;
        } else {
          datacenterId_ = null;
          datacenterIdBuilder_ = null;
        }
        if (serverPrivateIpAddressBuilder_ == null) {
          serverPrivateIpAddress_ = null;
        } else {
          serverPrivateIpAddress_ = null;
          serverPrivateIpAddressBuilder_ = null;
        }
        versionMajor_ = 0;

        versionMinor_ = 0;

        versionPatch_ = 0;

        datacenterEnabled_ = false;

        datacenterName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.server_ingress_data.ServerIngressData.internal_static_server_ingress_data_ServerIngressServerData_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData getDefaultInstanceForType() {
        return com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData build() {
        com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData buildPartial() {
        com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData result = new com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData(this);
        result.serverRoutePublicKey_ = serverRoutePublicKey_;
        if (datacenterIdBuilder_ == null) {
          result.datacenterId_ = datacenterId_;
        } else {
          result.datacenterId_ = datacenterIdBuilder_.build();
        }
        if (serverPrivateIpAddressBuilder_ == null) {
          result.serverPrivateIpAddress_ = serverPrivateIpAddress_;
        } else {
          result.serverPrivateIpAddress_ = serverPrivateIpAddressBuilder_.build();
        }
        result.versionMajor_ = versionMajor_;
        result.versionMinor_ = versionMinor_;
        result.versionPatch_ = versionPatch_;
        result.datacenterEnabled_ = datacenterEnabled_;
        result.datacenterName_ = datacenterName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData) {
          return mergeFrom((com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData other) {
        if (other == com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData.getDefaultInstance()) return this;
        if (other.getServerRoutePublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setServerRoutePublicKey(other.getServerRoutePublicKey());
        }
        if (other.hasDatacenterId()) {
          mergeDatacenterId(other.getDatacenterId());
        }
        if (other.hasServerPrivateIpAddress()) {
          mergeServerPrivateIpAddress(other.getServerPrivateIpAddress());
        }
        if (other.getVersionMajor() != 0) {
          setVersionMajor(other.getVersionMajor());
        }
        if (other.getVersionMinor() != 0) {
          setVersionMinor(other.getVersionMinor());
        }
        if (other.getVersionPatch() != 0) {
          setVersionPatch(other.getVersionPatch());
        }
        if (other.getDatacenterEnabled() != false) {
          setDatacenterEnabled(other.getDatacenterEnabled());
        }
        if (!other.getDatacenterName().isEmpty()) {
          datacenterName_ = other.datacenterName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString serverRoutePublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes serverRoutePublicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getServerRoutePublicKey() {
        return serverRoutePublicKey_;
      }
      /**
       * <code>bytes serverRoutePublicKey = 1;</code>
       */
      public Builder setServerRoutePublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverRoutePublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes serverRoutePublicKey = 1;</code>
       */
      public Builder clearServerRoutePublicKey() {
        
        serverRoutePublicKey_ = getDefaultInstance().getServerRoutePublicKey();
        onChanged();
        return this;
      }

      private com.networknext.api.id.Id.EntityId datacenterId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> datacenterIdBuilder_;
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public boolean hasDatacenterId() {
        return datacenterIdBuilder_ != null || datacenterId_ != null;
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityId getDatacenterId() {
        if (datacenterIdBuilder_ == null) {
          return datacenterId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : datacenterId_;
        } else {
          return datacenterIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public Builder setDatacenterId(com.networknext.api.id.Id.EntityId value) {
        if (datacenterIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          datacenterId_ = value;
          onChanged();
        } else {
          datacenterIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public Builder setDatacenterId(
          com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (datacenterIdBuilder_ == null) {
          datacenterId_ = builderForValue.build();
          onChanged();
        } else {
          datacenterIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public Builder mergeDatacenterId(com.networknext.api.id.Id.EntityId value) {
        if (datacenterIdBuilder_ == null) {
          if (datacenterId_ != null) {
            datacenterId_ =
              com.networknext.api.id.Id.EntityId.newBuilder(datacenterId_).mergeFrom(value).buildPartial();
          } else {
            datacenterId_ = value;
          }
          onChanged();
        } else {
          datacenterIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public Builder clearDatacenterId() {
        if (datacenterIdBuilder_ == null) {
          datacenterId_ = null;
          onChanged();
        } else {
          datacenterId_ = null;
          datacenterIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder getDatacenterIdBuilder() {
        
        onChanged();
        return getDatacenterIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityIdOrBuilder getDatacenterIdOrBuilder() {
        if (datacenterIdBuilder_ != null) {
          return datacenterIdBuilder_.getMessageOrBuilder();
        } else {
          return datacenterId_ == null ?
              com.networknext.api.id.Id.EntityId.getDefaultInstance() : datacenterId_;
        }
      }
      /**
       * <code>.id.EntityId datacenterId = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> 
          getDatacenterIdFieldBuilder() {
        if (datacenterIdBuilder_ == null) {
          datacenterIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder>(
                  getDatacenterId(),
                  getParentForChildren(),
                  isClean());
          datacenterId_ = null;
        }
        return datacenterIdBuilder_;
      }

      private com.networknext.api.address.AddressOuterClass.Address serverPrivateIpAddress_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder> serverPrivateIpAddressBuilder_;
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public boolean hasServerPrivateIpAddress() {
        return serverPrivateIpAddressBuilder_ != null || serverPrivateIpAddress_ != null;
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.Address getServerPrivateIpAddress() {
        if (serverPrivateIpAddressBuilder_ == null) {
          return serverPrivateIpAddress_ == null ? com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : serverPrivateIpAddress_;
        } else {
          return serverPrivateIpAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public Builder setServerPrivateIpAddress(com.networknext.api.address.AddressOuterClass.Address value) {
        if (serverPrivateIpAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverPrivateIpAddress_ = value;
          onChanged();
        } else {
          serverPrivateIpAddressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public Builder setServerPrivateIpAddress(
          com.networknext.api.address.AddressOuterClass.Address.Builder builderForValue) {
        if (serverPrivateIpAddressBuilder_ == null) {
          serverPrivateIpAddress_ = builderForValue.build();
          onChanged();
        } else {
          serverPrivateIpAddressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public Builder mergeServerPrivateIpAddress(com.networknext.api.address.AddressOuterClass.Address value) {
        if (serverPrivateIpAddressBuilder_ == null) {
          if (serverPrivateIpAddress_ != null) {
            serverPrivateIpAddress_ =
              com.networknext.api.address.AddressOuterClass.Address.newBuilder(serverPrivateIpAddress_).mergeFrom(value).buildPartial();
          } else {
            serverPrivateIpAddress_ = value;
          }
          onChanged();
        } else {
          serverPrivateIpAddressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public Builder clearServerPrivateIpAddress() {
        if (serverPrivateIpAddressBuilder_ == null) {
          serverPrivateIpAddress_ = null;
          onChanged();
        } else {
          serverPrivateIpAddress_ = null;
          serverPrivateIpAddressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.Address.Builder getServerPrivateIpAddressBuilder() {
        
        onChanged();
        return getServerPrivateIpAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.AddressOrBuilder getServerPrivateIpAddressOrBuilder() {
        if (serverPrivateIpAddressBuilder_ != null) {
          return serverPrivateIpAddressBuilder_.getMessageOrBuilder();
        } else {
          return serverPrivateIpAddress_ == null ?
              com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : serverPrivateIpAddress_;
        }
      }
      /**
       * <code>.address.Address serverPrivateIpAddress = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder> 
          getServerPrivateIpAddressFieldBuilder() {
        if (serverPrivateIpAddressBuilder_ == null) {
          serverPrivateIpAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder>(
                  getServerPrivateIpAddress(),
                  getParentForChildren(),
                  isClean());
          serverPrivateIpAddress_ = null;
        }
        return serverPrivateIpAddressBuilder_;
      }

      private int versionMajor_ ;
      /**
       * <code>int32 versionMajor = 4;</code>
       */
      public int getVersionMajor() {
        return versionMajor_;
      }
      /**
       * <code>int32 versionMajor = 4;</code>
       */
      public Builder setVersionMajor(int value) {
        
        versionMajor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 versionMajor = 4;</code>
       */
      public Builder clearVersionMajor() {
        
        versionMajor_ = 0;
        onChanged();
        return this;
      }

      private int versionMinor_ ;
      /**
       * <code>int32 versionMinor = 5;</code>
       */
      public int getVersionMinor() {
        return versionMinor_;
      }
      /**
       * <code>int32 versionMinor = 5;</code>
       */
      public Builder setVersionMinor(int value) {
        
        versionMinor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 versionMinor = 5;</code>
       */
      public Builder clearVersionMinor() {
        
        versionMinor_ = 0;
        onChanged();
        return this;
      }

      private int versionPatch_ ;
      /**
       * <code>int32 versionPatch = 6;</code>
       */
      public int getVersionPatch() {
        return versionPatch_;
      }
      /**
       * <code>int32 versionPatch = 6;</code>
       */
      public Builder setVersionPatch(int value) {
        
        versionPatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 versionPatch = 6;</code>
       */
      public Builder clearVersionPatch() {
        
        versionPatch_ = 0;
        onChanged();
        return this;
      }

      private boolean datacenterEnabled_ ;
      /**
       * <code>bool datacenterEnabled = 7;</code>
       */
      public boolean getDatacenterEnabled() {
        return datacenterEnabled_;
      }
      /**
       * <code>bool datacenterEnabled = 7;</code>
       */
      public Builder setDatacenterEnabled(boolean value) {
        
        datacenterEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool datacenterEnabled = 7;</code>
       */
      public Builder clearDatacenterEnabled() {
        
        datacenterEnabled_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object datacenterName_ = "";
      /**
       * <code>string datacenterName = 8;</code>
       */
      public java.lang.String getDatacenterName() {
        java.lang.Object ref = datacenterName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          datacenterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string datacenterName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDatacenterNameBytes() {
        java.lang.Object ref = datacenterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datacenterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string datacenterName = 8;</code>
       */
      public Builder setDatacenterName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        datacenterName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string datacenterName = 8;</code>
       */
      public Builder clearDatacenterName() {
        
        datacenterName_ = getDefaultInstance().getDatacenterName();
        onChanged();
        return this;
      }
      /**
       * <code>string datacenterName = 8;</code>
       */
      public Builder setDatacenterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        datacenterName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server_ingress_data.ServerIngressServerData)
    }

    // @@protoc_insertion_point(class_scope:server_ingress_data.ServerIngressServerData)
    private static final com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData();
    }

    public static com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerIngressServerData>
        PARSER = new com.google.protobuf.AbstractParser<ServerIngressServerData>() {
      @java.lang.Override
      public ServerIngressServerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerIngressServerData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerIngressServerData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerIngressServerData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.server_ingress_data.ServerIngressData.ServerIngressServerData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ingress_data_ServerIngressServerData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ingress_data_ServerIngressServerData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-server_ingress_data/server_ingress_dat" +
      "a.proto\022\023server_ingress_data\032\025address/ad" +
      "dress.proto\032\013id/id.proto\"\202\002\n\027ServerIngre" +
      "ssServerData\022\034\n\024serverRoutePublicKey\030\001 \001" +
      "(\014\022\"\n\014datacenterId\030\002 \001(\0132\014.id.EntityId\0220" +
      "\n\026serverPrivateIpAddress\030\003 \001(\0132\020.address" +
      ".Address\022\024\n\014versionMajor\030\004 \001(\005\022\024\n\014versio" +
      "nMinor\030\005 \001(\005\022\024\n\014versionPatch\030\006 \001(\005\022\031\n\021da" +
      "tacenterEnabled\030\007 \001(\010\022\026\n\016datacenterName\030" +
      "\010 \001(\tB>\n\'com.networknext.api.server_ingr" +
      "ess_dataZ\023server_ingress_datab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.address.AddressOuterClass.getDescriptor(),
          com.networknext.api.id.Id.getDescriptor(),
        }, assigner);
    internal_static_server_ingress_data_ServerIngressServerData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_ingress_data_ServerIngressServerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ingress_data_ServerIngressServerData_descriptor,
        new java.lang.String[] { "ServerRoutePublicKey", "DatacenterId", "ServerPrivateIpAddress", "VersionMajor", "VersionMinor", "VersionPatch", "DatacenterEnabled", "DatacenterName", });
    com.networknext.api.address.AddressOuterClass.getDescriptor();
    com.networknext.api.id.Id.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
