// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: near_data/near_data.proto

package com.networknext.api.near_data;

public final class NearData {
  private NearData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NearRelayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:near_data.NearRelay)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    boolean hasRelayId();
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    com.networknext.api.id.Id.EntityId getRelayId();
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder();

    /**
     * <code>double rtt = 2;</code>
     */
    double getRtt();

    /**
     * <code>double jitter = 3;</code>
     */
    double getJitter();

    /**
     * <code>double packetLoss = 4;</code>
     */
    double getPacketLoss();
  }
  /**
   * Protobuf type {@code near_data.NearRelay}
   */
  public  static final class NearRelay extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:near_data.NearRelay)
      NearRelayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NearRelay.newBuilder() to construct.
    private NearRelay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NearRelay() {
      rtt_ = 0D;
      jitter_ = 0D;
      packetLoss_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NearRelay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.networknext.api.id.Id.EntityId.Builder subBuilder = null;
              if (relayId_ != null) {
                subBuilder = relayId_.toBuilder();
              }
              relayId_ = input.readMessage(com.networknext.api.id.Id.EntityId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relayId_);
                relayId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 17: {

              rtt_ = input.readDouble();
              break;
            }
            case 25: {

              jitter_ = input.readDouble();
              break;
            }
            case 33: {

              packetLoss_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.near_data.NearData.internal_static_near_data_NearRelay_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.near_data.NearData.internal_static_near_data_NearRelay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.near_data.NearData.NearRelay.class, com.networknext.api.near_data.NearData.NearRelay.Builder.class);
    }

    public static final int RELAYID_FIELD_NUMBER = 1;
    private com.networknext.api.id.Id.EntityId relayId_;
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public boolean hasRelayId() {
      return relayId_ != null;
    }
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public com.networknext.api.id.Id.EntityId getRelayId() {
      return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
    }
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
      return getRelayId();
    }

    public static final int RTT_FIELD_NUMBER = 2;
    private double rtt_;
    /**
     * <code>double rtt = 2;</code>
     */
    public double getRtt() {
      return rtt_;
    }

    public static final int JITTER_FIELD_NUMBER = 3;
    private double jitter_;
    /**
     * <code>double jitter = 3;</code>
     */
    public double getJitter() {
      return jitter_;
    }

    public static final int PACKETLOSS_FIELD_NUMBER = 4;
    private double packetLoss_;
    /**
     * <code>double packetLoss = 4;</code>
     */
    public double getPacketLoss() {
      return packetLoss_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (relayId_ != null) {
        output.writeMessage(1, getRelayId());
      }
      if (rtt_ != 0D) {
        output.writeDouble(2, rtt_);
      }
      if (jitter_ != 0D) {
        output.writeDouble(3, jitter_);
      }
      if (packetLoss_ != 0D) {
        output.writeDouble(4, packetLoss_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (relayId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRelayId());
      }
      if (rtt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, rtt_);
      }
      if (jitter_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, jitter_);
      }
      if (packetLoss_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, packetLoss_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.near_data.NearData.NearRelay)) {
        return super.equals(obj);
      }
      com.networknext.api.near_data.NearData.NearRelay other = (com.networknext.api.near_data.NearData.NearRelay) obj;

      boolean result = true;
      result = result && (hasRelayId() == other.hasRelayId());
      if (hasRelayId()) {
        result = result && getRelayId()
            .equals(other.getRelayId());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getRtt())
          == java.lang.Double.doubleToLongBits(
              other.getRtt()));
      result = result && (
          java.lang.Double.doubleToLongBits(getJitter())
          == java.lang.Double.doubleToLongBits(
              other.getJitter()));
      result = result && (
          java.lang.Double.doubleToLongBits(getPacketLoss())
          == java.lang.Double.doubleToLongBits(
              other.getPacketLoss()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRelayId()) {
        hash = (37 * hash) + RELAYID_FIELD_NUMBER;
        hash = (53 * hash) + getRelayId().hashCode();
      }
      hash = (37 * hash) + RTT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRtt()));
      hash = (37 * hash) + JITTER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getJitter()));
      hash = (37 * hash) + PACKETLOSS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPacketLoss()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.NearRelay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.near_data.NearData.NearRelay prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code near_data.NearRelay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:near_data.NearRelay)
        com.networknext.api.near_data.NearData.NearRelayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_NearRelay_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_NearRelay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.near_data.NearData.NearRelay.class, com.networknext.api.near_data.NearData.NearRelay.Builder.class);
      }

      // Construct using com.networknext.api.near_data.NearData.NearRelay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (relayIdBuilder_ == null) {
          relayId_ = null;
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }
        rtt_ = 0D;

        jitter_ = 0D;

        packetLoss_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_NearRelay_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.NearRelay getDefaultInstanceForType() {
        return com.networknext.api.near_data.NearData.NearRelay.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.NearRelay build() {
        com.networknext.api.near_data.NearData.NearRelay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.NearRelay buildPartial() {
        com.networknext.api.near_data.NearData.NearRelay result = new com.networknext.api.near_data.NearData.NearRelay(this);
        if (relayIdBuilder_ == null) {
          result.relayId_ = relayId_;
        } else {
          result.relayId_ = relayIdBuilder_.build();
        }
        result.rtt_ = rtt_;
        result.jitter_ = jitter_;
        result.packetLoss_ = packetLoss_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.near_data.NearData.NearRelay) {
          return mergeFrom((com.networknext.api.near_data.NearData.NearRelay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.near_data.NearData.NearRelay other) {
        if (other == com.networknext.api.near_data.NearData.NearRelay.getDefaultInstance()) return this;
        if (other.hasRelayId()) {
          mergeRelayId(other.getRelayId());
        }
        if (other.getRtt() != 0D) {
          setRtt(other.getRtt());
        }
        if (other.getJitter() != 0D) {
          setJitter(other.getJitter());
        }
        if (other.getPacketLoss() != 0D) {
          setPacketLoss(other.getPacketLoss());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.near_data.NearData.NearRelay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.near_data.NearData.NearRelay) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.networknext.api.id.Id.EntityId relayId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> relayIdBuilder_;
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public boolean hasRelayId() {
        return relayIdBuilder_ != null || relayId_ != null;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityId getRelayId() {
        if (relayIdBuilder_ == null) {
          return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        } else {
          return relayIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder setRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relayId_ = value;
          onChanged();
        } else {
          relayIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder setRelayId(
          com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (relayIdBuilder_ == null) {
          relayId_ = builderForValue.build();
          onChanged();
        } else {
          relayIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder mergeRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (relayId_ != null) {
            relayId_ =
              com.networknext.api.id.Id.EntityId.newBuilder(relayId_).mergeFrom(value).buildPartial();
          } else {
            relayId_ = value;
          }
          onChanged();
        } else {
          relayIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder clearRelayId() {
        if (relayIdBuilder_ == null) {
          relayId_ = null;
          onChanged();
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder getRelayIdBuilder() {
        
        onChanged();
        return getRelayIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
        if (relayIdBuilder_ != null) {
          return relayIdBuilder_.getMessageOrBuilder();
        } else {
          return relayId_ == null ?
              com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        }
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> 
          getRelayIdFieldBuilder() {
        if (relayIdBuilder_ == null) {
          relayIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder>(
                  getRelayId(),
                  getParentForChildren(),
                  isClean());
          relayId_ = null;
        }
        return relayIdBuilder_;
      }

      private double rtt_ ;
      /**
       * <code>double rtt = 2;</code>
       */
      public double getRtt() {
        return rtt_;
      }
      /**
       * <code>double rtt = 2;</code>
       */
      public Builder setRtt(double value) {
        
        rtt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rtt = 2;</code>
       */
      public Builder clearRtt() {
        
        rtt_ = 0D;
        onChanged();
        return this;
      }

      private double jitter_ ;
      /**
       * <code>double jitter = 3;</code>
       */
      public double getJitter() {
        return jitter_;
      }
      /**
       * <code>double jitter = 3;</code>
       */
      public Builder setJitter(double value) {
        
        jitter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double jitter = 3;</code>
       */
      public Builder clearJitter() {
        
        jitter_ = 0D;
        onChanged();
        return this;
      }

      private double packetLoss_ ;
      /**
       * <code>double packetLoss = 4;</code>
       */
      public double getPacketLoss() {
        return packetLoss_;
      }
      /**
       * <code>double packetLoss = 4;</code>
       */
      public Builder setPacketLoss(double value) {
        
        packetLoss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double packetLoss = 4;</code>
       */
      public Builder clearPacketLoss() {
        
        packetLoss_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:near_data.NearRelay)
    }

    // @@protoc_insertion_point(class_scope:near_data.NearRelay)
    private static final com.networknext.api.near_data.NearData.NearRelay DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.near_data.NearData.NearRelay();
    }

    public static com.networknext.api.near_data.NearData.NearRelay getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NearRelay>
        PARSER = new com.google.protobuf.AbstractParser<NearRelay>() {
      @java.lang.Override
      public NearRelay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NearRelay(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NearRelay> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NearRelay> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.near_data.NearData.NearRelay getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IssuedNearRelayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:near_data.IssuedNearRelay)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     */
    int getIndex();

    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    boolean hasRelayId();
    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    com.networknext.api.id.Id.EntityId getRelayId();
    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder();

    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    boolean hasRelayIpAddress();
    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    com.networknext.api.address.AddressOuterClass.Address getRelayIpAddress();
    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    com.networknext.api.address.AddressOuterClass.AddressOrBuilder getRelayIpAddressOrBuilder();
  }
  /**
   * Protobuf type {@code near_data.IssuedNearRelay}
   */
  public  static final class IssuedNearRelay extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:near_data.IssuedNearRelay)
      IssuedNearRelayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IssuedNearRelay.newBuilder() to construct.
    private IssuedNearRelay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IssuedNearRelay() {
      index_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IssuedNearRelay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 18: {
              com.networknext.api.id.Id.EntityId.Builder subBuilder = null;
              if (relayId_ != null) {
                subBuilder = relayId_.toBuilder();
              }
              relayId_ = input.readMessage(com.networknext.api.id.Id.EntityId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relayId_);
                relayId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.networknext.api.address.AddressOuterClass.Address.Builder subBuilder = null;
              if (relayIpAddress_ != null) {
                subBuilder = relayIpAddress_.toBuilder();
              }
              relayIpAddress_ = input.readMessage(com.networknext.api.address.AddressOuterClass.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relayIpAddress_);
                relayIpAddress_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.near_data.NearData.internal_static_near_data_IssuedNearRelay_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.near_data.NearData.internal_static_near_data_IssuedNearRelay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.near_data.NearData.IssuedNearRelay.class, com.networknext.api.near_data.NearData.IssuedNearRelay.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int RELAYID_FIELD_NUMBER = 2;
    private com.networknext.api.id.Id.EntityId relayId_;
    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    public boolean hasRelayId() {
      return relayId_ != null;
    }
    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    public com.networknext.api.id.Id.EntityId getRelayId() {
      return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
    }
    /**
     * <code>.id.EntityId relayId = 2;</code>
     */
    public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
      return getRelayId();
    }

    public static final int RELAYIPADDRESS_FIELD_NUMBER = 3;
    private com.networknext.api.address.AddressOuterClass.Address relayIpAddress_;
    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    public boolean hasRelayIpAddress() {
      return relayIpAddress_ != null;
    }
    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    public com.networknext.api.address.AddressOuterClass.Address getRelayIpAddress() {
      return relayIpAddress_ == null ? com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : relayIpAddress_;
    }
    /**
     * <code>.address.Address relayIpAddress = 3;</code>
     */
    public com.networknext.api.address.AddressOuterClass.AddressOrBuilder getRelayIpAddressOrBuilder() {
      return getRelayIpAddress();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (relayId_ != null) {
        output.writeMessage(2, getRelayId());
      }
      if (relayIpAddress_ != null) {
        output.writeMessage(3, getRelayIpAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (relayId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRelayId());
      }
      if (relayIpAddress_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRelayIpAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.near_data.NearData.IssuedNearRelay)) {
        return super.equals(obj);
      }
      com.networknext.api.near_data.NearData.IssuedNearRelay other = (com.networknext.api.near_data.NearData.IssuedNearRelay) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && (hasRelayId() == other.hasRelayId());
      if (hasRelayId()) {
        result = result && getRelayId()
            .equals(other.getRelayId());
      }
      result = result && (hasRelayIpAddress() == other.hasRelayIpAddress());
      if (hasRelayIpAddress()) {
        result = result && getRelayIpAddress()
            .equals(other.getRelayIpAddress());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      if (hasRelayId()) {
        hash = (37 * hash) + RELAYID_FIELD_NUMBER;
        hash = (53 * hash) + getRelayId().hashCode();
      }
      if (hasRelayIpAddress()) {
        hash = (37 * hash) + RELAYIPADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getRelayIpAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near_data.NearData.IssuedNearRelay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.near_data.NearData.IssuedNearRelay prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code near_data.IssuedNearRelay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:near_data.IssuedNearRelay)
        com.networknext.api.near_data.NearData.IssuedNearRelayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_IssuedNearRelay_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_IssuedNearRelay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.near_data.NearData.IssuedNearRelay.class, com.networknext.api.near_data.NearData.IssuedNearRelay.Builder.class);
      }

      // Construct using com.networknext.api.near_data.NearData.IssuedNearRelay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        if (relayIdBuilder_ == null) {
          relayId_ = null;
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }
        if (relayIpAddressBuilder_ == null) {
          relayIpAddress_ = null;
        } else {
          relayIpAddress_ = null;
          relayIpAddressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.near_data.NearData.internal_static_near_data_IssuedNearRelay_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.IssuedNearRelay getDefaultInstanceForType() {
        return com.networknext.api.near_data.NearData.IssuedNearRelay.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.IssuedNearRelay build() {
        com.networknext.api.near_data.NearData.IssuedNearRelay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.near_data.NearData.IssuedNearRelay buildPartial() {
        com.networknext.api.near_data.NearData.IssuedNearRelay result = new com.networknext.api.near_data.NearData.IssuedNearRelay(this);
        result.index_ = index_;
        if (relayIdBuilder_ == null) {
          result.relayId_ = relayId_;
        } else {
          result.relayId_ = relayIdBuilder_.build();
        }
        if (relayIpAddressBuilder_ == null) {
          result.relayIpAddress_ = relayIpAddress_;
        } else {
          result.relayIpAddress_ = relayIpAddressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.near_data.NearData.IssuedNearRelay) {
          return mergeFrom((com.networknext.api.near_data.NearData.IssuedNearRelay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.near_data.NearData.IssuedNearRelay other) {
        if (other == com.networknext.api.near_data.NearData.IssuedNearRelay.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.hasRelayId()) {
          mergeRelayId(other.getRelayId());
        }
        if (other.hasRelayIpAddress()) {
          mergeRelayIpAddress(other.getRelayIpAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.near_data.NearData.IssuedNearRelay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.near_data.NearData.IssuedNearRelay) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private com.networknext.api.id.Id.EntityId relayId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> relayIdBuilder_;
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public boolean hasRelayId() {
        return relayIdBuilder_ != null || relayId_ != null;
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityId getRelayId() {
        if (relayIdBuilder_ == null) {
          return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        } else {
          return relayIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public Builder setRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relayId_ = value;
          onChanged();
        } else {
          relayIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public Builder setRelayId(
          com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (relayIdBuilder_ == null) {
          relayId_ = builderForValue.build();
          onChanged();
        } else {
          relayIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public Builder mergeRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (relayId_ != null) {
            relayId_ =
              com.networknext.api.id.Id.EntityId.newBuilder(relayId_).mergeFrom(value).buildPartial();
          } else {
            relayId_ = value;
          }
          onChanged();
        } else {
          relayIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public Builder clearRelayId() {
        if (relayIdBuilder_ == null) {
          relayId_ = null;
          onChanged();
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder getRelayIdBuilder() {
        
        onChanged();
        return getRelayIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
        if (relayIdBuilder_ != null) {
          return relayIdBuilder_.getMessageOrBuilder();
        } else {
          return relayId_ == null ?
              com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        }
      }
      /**
       * <code>.id.EntityId relayId = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> 
          getRelayIdFieldBuilder() {
        if (relayIdBuilder_ == null) {
          relayIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder>(
                  getRelayId(),
                  getParentForChildren(),
                  isClean());
          relayId_ = null;
        }
        return relayIdBuilder_;
      }

      private com.networknext.api.address.AddressOuterClass.Address relayIpAddress_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder> relayIpAddressBuilder_;
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public boolean hasRelayIpAddress() {
        return relayIpAddressBuilder_ != null || relayIpAddress_ != null;
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.Address getRelayIpAddress() {
        if (relayIpAddressBuilder_ == null) {
          return relayIpAddress_ == null ? com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : relayIpAddress_;
        } else {
          return relayIpAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public Builder setRelayIpAddress(com.networknext.api.address.AddressOuterClass.Address value) {
        if (relayIpAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relayIpAddress_ = value;
          onChanged();
        } else {
          relayIpAddressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public Builder setRelayIpAddress(
          com.networknext.api.address.AddressOuterClass.Address.Builder builderForValue) {
        if (relayIpAddressBuilder_ == null) {
          relayIpAddress_ = builderForValue.build();
          onChanged();
        } else {
          relayIpAddressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public Builder mergeRelayIpAddress(com.networknext.api.address.AddressOuterClass.Address value) {
        if (relayIpAddressBuilder_ == null) {
          if (relayIpAddress_ != null) {
            relayIpAddress_ =
              com.networknext.api.address.AddressOuterClass.Address.newBuilder(relayIpAddress_).mergeFrom(value).buildPartial();
          } else {
            relayIpAddress_ = value;
          }
          onChanged();
        } else {
          relayIpAddressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public Builder clearRelayIpAddress() {
        if (relayIpAddressBuilder_ == null) {
          relayIpAddress_ = null;
          onChanged();
        } else {
          relayIpAddress_ = null;
          relayIpAddressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.Address.Builder getRelayIpAddressBuilder() {
        
        onChanged();
        return getRelayIpAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      public com.networknext.api.address.AddressOuterClass.AddressOrBuilder getRelayIpAddressOrBuilder() {
        if (relayIpAddressBuilder_ != null) {
          return relayIpAddressBuilder_.getMessageOrBuilder();
        } else {
          return relayIpAddress_ == null ?
              com.networknext.api.address.AddressOuterClass.Address.getDefaultInstance() : relayIpAddress_;
        }
      }
      /**
       * <code>.address.Address relayIpAddress = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder> 
          getRelayIpAddressFieldBuilder() {
        if (relayIpAddressBuilder_ == null) {
          relayIpAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.address.AddressOuterClass.Address, com.networknext.api.address.AddressOuterClass.Address.Builder, com.networknext.api.address.AddressOuterClass.AddressOrBuilder>(
                  getRelayIpAddress(),
                  getParentForChildren(),
                  isClean());
          relayIpAddress_ = null;
        }
        return relayIpAddressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:near_data.IssuedNearRelay)
    }

    // @@protoc_insertion_point(class_scope:near_data.IssuedNearRelay)
    private static final com.networknext.api.near_data.NearData.IssuedNearRelay DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.near_data.NearData.IssuedNearRelay();
    }

    public static com.networknext.api.near_data.NearData.IssuedNearRelay getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IssuedNearRelay>
        PARSER = new com.google.protobuf.AbstractParser<IssuedNearRelay>() {
      @java.lang.Override
      public IssuedNearRelay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IssuedNearRelay(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IssuedNearRelay> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IssuedNearRelay> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.near_data.NearData.IssuedNearRelay getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_near_data_NearRelay_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_near_data_NearRelay_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_near_data_IssuedNearRelay_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_near_data_IssuedNearRelay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031near_data/near_data.proto\022\tnear_data\032\025" +
      "address/address.proto\032\013id/id.proto\"[\n\tNe" +
      "arRelay\022\035\n\007relayId\030\001 \001(\0132\014.id.EntityId\022\013" +
      "\n\003rtt\030\002 \001(\001\022\016\n\006jitter\030\003 \001(\001\022\022\n\npacketLos" +
      "s\030\004 \001(\001\"i\n\017IssuedNearRelay\022\r\n\005index\030\001 \001(" +
      "\005\022\035\n\007relayId\030\002 \001(\0132\014.id.EntityId\022(\n\016rela" +
      "yIpAddress\030\003 \001(\0132\020.address.AddressB*\n\035co" +
      "m.networknext.api.near_dataZ\tnear_datab\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.address.AddressOuterClass.getDescriptor(),
          com.networknext.api.id.Id.getDescriptor(),
        }, assigner);
    internal_static_near_data_NearRelay_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_near_data_NearRelay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_near_data_NearRelay_descriptor,
        new java.lang.String[] { "RelayId", "Rtt", "Jitter", "PacketLoss", });
    internal_static_near_data_IssuedNearRelay_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_near_data_IssuedNearRelay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_near_data_IssuedNearRelay_descriptor,
        new java.lang.String[] { "Index", "RelayId", "RelayIpAddress", });
    com.networknext.api.address.AddressOuterClass.getDescriptor();
    com.networknext.api.id.Id.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
