// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_ingress/server_ingress.proto

package com.networknext.api.server_ingress;

public final class ServerIngress {
  private ServerIngress() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#server_ingress/server_ingress.proto\022\016s" +
      "erver_ingress\032-data_forward_common/data_" +
      "forward_common.proto2\347\001\n\024ServerIngressSe" +
      "rvice\022c\n\014ServerUpdate\022\'.data_forward_com" +
      "mon.DataForwardRequest\032(.data_forward_co" +
      "mmon.DataForwardResponse\"\000\022j\n\023ServerSess" +
      "ionUpdate\022\'.data_forward_common.DataForw" +
      "ardRequest\032(.data_forward_common.DataFor" +
      "wardResponse\"\000B4\n\"com.networknext.api.se" +
      "rver_ingressZ\016server_ingressb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor(),
        }, assigner);
    com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
