// Code generated by protoc-gen-go. DO NOT EDIT.
// source: id/id.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This is a typed ID in the Network Next API.
type EntityId struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityId) Reset()         { *m = EntityId{} }
func (m *EntityId) String() string { return proto.CompactTextString(m) }
func (*EntityId) ProtoMessage()    {}
func (*EntityId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec0ede66f5e76b8, []int{0}
}

func (m *EntityId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityId.Unmarshal(m, b)
}
func (m *EntityId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityId.Marshal(b, m, deterministic)
}
func (m *EntityId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityId.Merge(m, src)
}
func (m *EntityId) XXX_Size() int {
	return xxx_messageInfo_EntityId.Size(m)
}
func (m *EntityId) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityId.DiscardUnknown(m)
}

var xxx_messageInfo_EntityId proto.InternalMessageInfo

func (m *EntityId) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *EntityId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*EntityId)(nil), "id.EntityId")
}

func init() { proto.RegisterFile("id/id.proto", fileDescriptor_4ec0ede66f5e76b8) }

var fileDescriptor_4ec0ede66f5e76b8 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4c, 0xd1, 0xcf,
	0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x4c, 0x51, 0x32, 0xe2, 0xe2, 0x70,
	0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0xf4, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0xce, 0xcc, 0x4b, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c,
	0x10, 0x31, 0x10, 0xdb, 0x49, 0x86, 0x4b, 0x2c, 0x39, 0x3f, 0x57, 0x2f, 0x2f, 0xb5, 0xa4, 0x3c,
	0xbf, 0x28, 0x3b, 0x2f, 0xb5, 0xa2, 0x44, 0x2f, 0xb1, 0x20, 0x53, 0x2f, 0x33, 0x25, 0x8a, 0x29,
	0x33, 0x25, 0x89, 0x0d, 0x6c, 0xb8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xb5, 0x8d, 0xb1,
	0x6b, 0x00, 0x00, 0x00,
}
