@startuml Overview
node NetworkNext {
    database BigQuery
    database Firestore
    database RedisRelays
    database RedisPortal
    database RedisCache

    node Portal [
        Portal

        - RPC API
        - Web UI
    ]
    node RelayBackend [
        RelayBackend

        - Cost Matrix
        - Route Matrix
    ]
    node ServerBackend [
        ServerBackend

        - Instance1
        - Instance2
        - InstanceN
    ]
}

cloud Internet {
    node Auth0
    node Relays [
        1..N Relays
    ]
    node GameServer
    node GameClient
}

RelayBackend <..> Relays : Ping Stats (1s)
RelayBackend <..> RedisRelays : Read/Write active\nRelay data
RelayBackend <.. Firestore : Sync Relays (1s)
RelayBackend ..> Firestore : Set Relay State

GameServer <..> GameClient : Direct Route
GameClient <..> Relays : Next Route\nHop 0
GameServer <..> Relays : Next Route\nHop (3..5)
ServerBackend <..> GameServer : Session Updates (10s)
ServerBackend <..> GameServer : Server Updates (10s)
ServerBackend <.. Firestore : Syncs Buyers\n&\nDatacenters (1s)
ServerBackend <.. RelayBackend : Syncs Route Matrix (1s)
ServerBackend <.. RedisRelays : Relays Near\nClient IP
ServerBackend <..> RedisCache : Read/Write active\nServer and Session\ndata
ServerBackend ..> RedisPortal : Write Map, Session,\nand User data

ServerBackend ..> BigQuery : Billing Slice Entries

Portal <.. Firestore : Syncs Buyers\n&\nDatacenters (1s)
Portal <.. RedisPortal : Read Map, Session,\nand User data
Portal <.. RedisRelays : Relay data for\nOps Service
Portal <..> Auth0 : User Accounts
@enduml

