@startuml Relay States
Enabled : Relay is online and\ncommunicating with\nthe backend
Offline : Relay is operating\nbut isn't communicating\nwith the backend yet
Quarantined : Relay has disconnected\nfor some reason and is\nawaiting operator\napproval before going\nback online
Maintenance : Relay has cleanly\nshut down
Disabled : Relay has been\nmanually shut down
Decommissioned : Final state before\npermanent shutdown

[*] --> Offline : startup
Offline --> Enabled : connected
Offline --> Disabled : `next relay disable`
Enabled --> Quarantined : disconnected
Enabled --> Maintenance : clean shutdown
Enabled --> Disabled : `next relay disable`
Maintenance --> Enabled : automatic restart
Maintenance --> Offline : `next relay enable`
Quarantined --> Offline : `next relay enable`
Quarantined --> Disabled : `next relay disable`
Maintenance --> Disabled : `next relay disable`
Disabled --> Offline : `next relay enable`
Disabled --> Decommissioned : `next relay remove`
Decommissioned --> [*]
@enduml

