MAKEFILE_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

include $(MAKEFILE_DIR)/Makefile.common

############
### Vars ###
############

EXE										:= relay.test

SRC_OBJ_FILES					:= $(patsubst $(SRC)/%.cpp, $(OBJ)/%.test.o, $(SRC_FILES))
SRC_DEP_FILES					:= $(patsubst $(SRC)/%.cpp, $(OBJ)/%.test.d, $(SRC_FILES))

COMMON_FLAGS 					:= $(CXX) $(CXX_FLAGS) $(CXX_DBG_FLAGS)
COMMON_COMPILE_FLAGS 	:= $(COMMON_FLAGS) -c -DTEST_BUILD 

################
### Targets  ###
################

.PHONY: all
all:  $(BIN)/$(EXE)

.PHONY: run
run: $(BIN)/$(EXE)
	@$<

.PHONY: clean
clean: 
	@rm -f $(BIN)/$(EXE) $(SRC_OBJ_FILES) $(SRC_DEP_FILES) $(GCH)

##############
### Builds ###
##############

# precompiled header
$(GCH): $(PCH) Makefile
	$(COMMON_COMPILE_FLAGS) -o $@ -x c++-header $<

# all object files
$(OBJ)/%.test.o: $(SRC)/%.cpp $(GCH)
	$(COMMON_COMPILE_FLAGS) -o $@ $(INCLUDE_DIRS) -MMD -MP $<

# the executable
$(BIN)/$(EXE): $(SRC_OBJ_FILES)
	$(COMMON_FLAGS) -o $@ $^ $(LIBRARIES)

-include $(SRC_DEP_FILES)

