include Makefile.common

################
### Targets  ###
################

RELEASE_EXE 			= bin/relay
RELEASE_ARTIFACT	= relay.release.tar.gz

DIST_DIR 					= dist
DIST_FILES				= $(DIST_DIR)/relay.env $(DIST_DIR)/relay.service $(DIST_DIR)/install.sh

release:
	@printf 'Building relay artifact...'
	tar -zcf $(RELEASE_ARTIFACT) $(RELEASE_EXE) $(DIST_FILES)
	@printf '$(RELEASE_ARTIFACT)'

