// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ip2location/ip2location.proto

package com.networknext.api.ip2location;

public final class Ip2Location {
  private Ip2Location() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ip2location.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string countryCode = 1;</code>
     */
    java.lang.String getCountryCode();
    /**
     * <code>string countryCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>string country = 2;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string region = 3;</code>
     */
    java.lang.String getRegion();
    /**
     * <code>string region = 3;</code>
     */
    com.google.protobuf.ByteString
        getRegionBytes();

    /**
     * <code>string city = 4;</code>
     */
    java.lang.String getCity();
    /**
     * <code>string city = 4;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>float latitude = 5;</code>
     */
    float getLatitude();

    /**
     * <code>float longitude = 6;</code>
     */
    float getLongitude();

    /**
     * <code>string isp = 7;</code>
     */
    java.lang.String getIsp();
    /**
     * <code>string isp = 7;</code>
     */
    com.google.protobuf.ByteString
        getIspBytes();

    /**
     * <code>int64 asn = 8;</code>
     */
    long getAsn();

    /**
     * <code>string continent = 9;</code>
     */
    java.lang.String getContinent();
    /**
     * <code>string continent = 9;</code>
     */
    com.google.protobuf.ByteString
        getContinentBytes();
  }
  /**
   * Protobuf type {@code ip2location.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ip2location.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      countryCode_ = "";
      country_ = "";
      region_ = "";
      city_ = "";
      latitude_ = 0F;
      longitude_ = 0F;
      isp_ = "";
      asn_ = 0L;
      continent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              countryCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              region_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 45: {

              latitude_ = input.readFloat();
              break;
            }
            case 53: {

              longitude_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              isp_ = s;
              break;
            }
            case 64: {

              asn_ = input.readInt64();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              continent_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.ip2location.Ip2Location.internal_static_ip2location_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.ip2location.Ip2Location.internal_static_ip2location_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.ip2location.Ip2Location.Location.class, com.networknext.api.ip2location.Ip2Location.Location.Builder.class);
    }

    public static final int COUNTRYCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object countryCode_;
    /**
     * <code>string countryCode = 1;</code>
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string countryCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 2;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 2;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 3;
    private volatile java.lang.Object region_;
    /**
     * <code>string region = 3;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      }
    }
    /**
     * <code>string region = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 4;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 5;
    private float latitude_;
    /**
     * <code>float latitude = 5;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private float longitude_;
    /**
     * <code>float longitude = 6;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    public static final int ISP_FIELD_NUMBER = 7;
    private volatile java.lang.Object isp_;
    /**
     * <code>string isp = 7;</code>
     */
    public java.lang.String getIsp() {
      java.lang.Object ref = isp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isp_ = s;
        return s;
      }
    }
    /**
     * <code>string isp = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIspBytes() {
      java.lang.Object ref = isp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASN_FIELD_NUMBER = 8;
    private long asn_;
    /**
     * <code>int64 asn = 8;</code>
     */
    public long getAsn() {
      return asn_;
    }

    public static final int CONTINENT_FIELD_NUMBER = 9;
    private volatile java.lang.Object continent_;
    /**
     * <code>string continent = 9;</code>
     */
    public java.lang.String getContinent() {
      java.lang.Object ref = continent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        continent_ = s;
        return s;
      }
    }
    /**
     * <code>string continent = 9;</code>
     */
    public com.google.protobuf.ByteString
        getContinentBytes() {
      java.lang.Object ref = continent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        continent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCountryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, countryCode_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, country_);
      }
      if (!getRegionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, region_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
      }
      if (latitude_ != 0F) {
        output.writeFloat(5, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(6, longitude_);
      }
      if (!getIspBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, isp_);
      }
      if (asn_ != 0L) {
        output.writeInt64(8, asn_);
      }
      if (!getContinentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, continent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCountryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, countryCode_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, country_);
      }
      if (!getRegionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, region_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
      }
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, longitude_);
      }
      if (!getIspBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, isp_);
      }
      if (asn_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, asn_);
      }
      if (!getContinentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, continent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.ip2location.Ip2Location.Location)) {
        return super.equals(obj);
      }
      com.networknext.api.ip2location.Ip2Location.Location other = (com.networknext.api.ip2location.Ip2Location.Location) obj;

      boolean result = true;
      result = result && getCountryCode()
          .equals(other.getCountryCode());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getRegion()
          .equals(other.getRegion());
      result = result && getCity()
          .equals(other.getCity());
      result = result && (
          java.lang.Float.floatToIntBits(getLatitude())
          == java.lang.Float.floatToIntBits(
              other.getLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getLongitude())
          == java.lang.Float.floatToIntBits(
              other.getLongitude()));
      result = result && getIsp()
          .equals(other.getIsp());
      result = result && (getAsn()
          == other.getAsn());
      result = result && getContinent()
          .equals(other.getContinent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTRYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (37 * hash) + ISP_FIELD_NUMBER;
      hash = (53 * hash) + getIsp().hashCode();
      hash = (37 * hash) + ASN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAsn());
      hash = (37 * hash) + CONTINENT_FIELD_NUMBER;
      hash = (53 * hash) + getContinent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.ip2location.Ip2Location.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.ip2location.Ip2Location.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ip2location.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ip2location.Location)
        com.networknext.api.ip2location.Ip2Location.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.ip2location.Ip2Location.internal_static_ip2location_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.ip2location.Ip2Location.internal_static_ip2location_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.ip2location.Ip2Location.Location.class, com.networknext.api.ip2location.Ip2Location.Location.Builder.class);
      }

      // Construct using com.networknext.api.ip2location.Ip2Location.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        countryCode_ = "";

        country_ = "";

        region_ = "";

        city_ = "";

        latitude_ = 0F;

        longitude_ = 0F;

        isp_ = "";

        asn_ = 0L;

        continent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.ip2location.Ip2Location.internal_static_ip2location_Location_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.ip2location.Ip2Location.Location getDefaultInstanceForType() {
        return com.networknext.api.ip2location.Ip2Location.Location.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.ip2location.Ip2Location.Location build() {
        com.networknext.api.ip2location.Ip2Location.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.ip2location.Ip2Location.Location buildPartial() {
        com.networknext.api.ip2location.Ip2Location.Location result = new com.networknext.api.ip2location.Ip2Location.Location(this);
        result.countryCode_ = countryCode_;
        result.country_ = country_;
        result.region_ = region_;
        result.city_ = city_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.isp_ = isp_;
        result.asn_ = asn_;
        result.continent_ = continent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.ip2location.Ip2Location.Location) {
          return mergeFrom((com.networknext.api.ip2location.Ip2Location.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.ip2location.Ip2Location.Location other) {
        if (other == com.networknext.api.ip2location.Ip2Location.Location.getDefaultInstance()) return this;
        if (!other.getCountryCode().isEmpty()) {
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getRegion().isEmpty()) {
          region_ = other.region_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        if (!other.getIsp().isEmpty()) {
          isp_ = other.isp_;
          onChanged();
        }
        if (other.getAsn() != 0L) {
          setAsn(other.getAsn());
        }
        if (!other.getContinent().isEmpty()) {
          continent_ = other.continent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.ip2location.Ip2Location.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.ip2location.Ip2Location.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>string countryCode = 1;</code>
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string countryCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryCode = 1;</code>
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 1;</code>
       */
      public Builder clearCountryCode() {
        
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 1;</code>
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 2;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 2;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 2;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 2;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <code>string region = 3;</code>
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          region_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string region = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string region = 3;</code>
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string region = 3;</code>
       */
      public Builder clearRegion() {
        
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <code>string region = 3;</code>
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        region_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 4;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private float latitude_ ;
      /**
       * <code>float latitude = 5;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>float latitude = 5;</code>
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float latitude = 5;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>float longitude = 6;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>float longitude = 6;</code>
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float longitude = 6;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object isp_ = "";
      /**
       * <code>string isp = 7;</code>
       */
      public java.lang.String getIsp() {
        java.lang.Object ref = isp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isp = 7;</code>
       */
      public com.google.protobuf.ByteString
          getIspBytes() {
        java.lang.Object ref = isp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isp = 7;</code>
       */
      public Builder setIsp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isp = 7;</code>
       */
      public Builder clearIsp() {
        
        isp_ = getDefaultInstance().getIsp();
        onChanged();
        return this;
      }
      /**
       * <code>string isp = 7;</code>
       */
      public Builder setIspBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isp_ = value;
        onChanged();
        return this;
      }

      private long asn_ ;
      /**
       * <code>int64 asn = 8;</code>
       */
      public long getAsn() {
        return asn_;
      }
      /**
       * <code>int64 asn = 8;</code>
       */
      public Builder setAsn(long value) {
        
        asn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 asn = 8;</code>
       */
      public Builder clearAsn() {
        
        asn_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object continent_ = "";
      /**
       * <code>string continent = 9;</code>
       */
      public java.lang.String getContinent() {
        java.lang.Object ref = continent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          continent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string continent = 9;</code>
       */
      public com.google.protobuf.ByteString
          getContinentBytes() {
        java.lang.Object ref = continent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          continent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string continent = 9;</code>
       */
      public Builder setContinent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        continent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string continent = 9;</code>
       */
      public Builder clearContinent() {
        
        continent_ = getDefaultInstance().getContinent();
        onChanged();
        return this;
      }
      /**
       * <code>string continent = 9;</code>
       */
      public Builder setContinentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        continent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ip2location.Location)
    }

    // @@protoc_insertion_point(class_scope:ip2location.Location)
    private static final com.networknext.api.ip2location.Ip2Location.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.ip2location.Ip2Location.Location();
    }

    public static com.networknext.api.ip2location.Ip2Location.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.ip2location.Ip2Location.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ip2location_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ip2location_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ip2location/ip2location.proto\022\013ip2loca" +
      "tion\032\025address/address.proto\032-data_forwar" +
      "d_common/data_forward_common.proto\"\240\001\n\010L" +
      "ocation\022\023\n\013countryCode\030\001 \001(\t\022\017\n\007country\030" +
      "\002 \001(\t\022\016\n\006region\030\003 \001(\t\022\014\n\004city\030\004 \001(\t\022\020\n\010l" +
      "atitude\030\005 \001(\002\022\021\n\tlongitude\030\006 \001(\002\022\013\n\003isp\030" +
      "\007 \001(\t\022\013\n\003asn\030\010 \001(\003\022\021\n\tcontinent\030\t \001(\t2H\n" +
      "\022IP2LocationService\0222\n\005Query\022\020.address.A" +
      "ddress\032\025.ip2location.Location\"\000B.\n\037com.n" +
      "etworknext.api.ip2locationZ\013ip2locationb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.address.AddressOuterClass.getDescriptor(),
          com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor(),
        }, assigner);
    internal_static_ip2location_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ip2location_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ip2location_Location_descriptor,
        new java.lang.String[] { "CountryCode", "Country", "Region", "City", "Latitude", "Longitude", "Isp", "Asn", "Continent", });
    com.networknext.api.address.AddressOuterClass.getDescriptor();
    com.networknext.api.data_forward_common.DataForwardCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
