// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"sync"
)

var (
	lockMatrixStoreMockDeleteMatrixSvc       sync.RWMutex
	lockMatrixStoreMockDeleteOptimizerMatrix sync.RWMutex
	lockMatrixStoreMockGetLiveMatrix         sync.RWMutex
	lockMatrixStoreMockGetMatrixSvcMaster    sync.RWMutex
	lockMatrixStoreMockGetMatrixSvcs         sync.RWMutex
	lockMatrixStoreMockGetOptimizerMaster    sync.RWMutex
	lockMatrixStoreMockGetOptimizerMatrices  sync.RWMutex
	lockMatrixStoreMockUpdateLiveMatrix      sync.RWMutex
	lockMatrixStoreMockUpdateMatrixSvc       sync.RWMutex
	lockMatrixStoreMockUpdateMatrixSvcMaster sync.RWMutex
	lockMatrixStoreMockUpdateOptimizerMaster sync.RWMutex
	lockMatrixStoreMockUpdateOptimizerMatrix sync.RWMutex
)

// Ensure, that MatrixStoreMock does implement MatrixStore.
// If this is not the case, regenerate this file with moq.
var _ MatrixStore = &MatrixStoreMock{}

// MatrixStoreMock is a mock implementation of MatrixStore.
//
//     func TestSomethingThatUsesMatrixStore(t *testing.T) {
//
//         // make and configure a mocked MatrixStore
//         mockedMatrixStore := &MatrixStoreMock{
//             DeleteMatrixSvcFunc: func(id uint64) error {
// 	               panic("mock out the DeleteMatrixSvc method")
//             },
//             DeleteOptimizerMatrixFunc: func(id uint64) error {
// 	               panic("mock out the DeleteOptimizerMatrix method")
//             },
//             GetLiveMatrixFunc: func() ([]byte, error) {
// 	               panic("mock out the GetLiveMatrix method")
//             },
//             GetMatrixSvcMasterFunc: func() (uint64, error) {
// 	               panic("mock out the GetMatrixSvcMaster method")
//             },
//             GetMatrixSvcsFunc: func() ([]MatrixSvcData, error) {
// 	               panic("mock out the GetMatrixSvcs method")
//             },
//             GetOptimizerMasterFunc: func() (uint64, error) {
// 	               panic("mock out the GetOptimizerMaster method")
//             },
//             GetOptimizerMatricesFunc: func() ([]Matrix, error) {
// 	               panic("mock out the GetOptimizerMatrices method")
//             },
//             UpdateLiveMatrixFunc: func(matrixData []byte) error {
// 	               panic("mock out the UpdateLiveMatrix method")
//             },
//             UpdateMatrixSvcFunc: func(matrixSvcData MatrixSvcData) error {
// 	               panic("mock out the UpdateMatrixSvc method")
//             },
//             UpdateMatrixSvcMasterFunc: func(id uint64) error {
// 	               panic("mock out the UpdateMatrixSvcMaster method")
//             },
//             UpdateOptimizerMasterFunc: func(id uint64) error {
// 	               panic("mock out the UpdateOptimizerMaster method")
//             },
//             UpdateOptimizerMatrixFunc: func(matrix Matrix) error {
// 	               panic("mock out the UpdateOptimizerMatrix method")
//             },
//         }
//
//         // use mockedMatrixStore in code that requires MatrixStore
//         // and then make assertions.
//
//     }
type MatrixStoreMock struct {
	// DeleteMatrixSvcFunc mocks the DeleteMatrixSvc method.
	DeleteMatrixSvcFunc func(id uint64) error

	// DeleteOptimizerMatrixFunc mocks the DeleteOptimizerMatrix method.
	DeleteOptimizerMatrixFunc func(id uint64) error

	// GetLiveMatrixFunc mocks the GetLiveMatrix method.
	GetLiveMatrixFunc func() ([]byte, error)

	// GetMatrixSvcMasterFunc mocks the GetMatrixSvcMaster method.
	GetMatrixSvcMasterFunc func() (uint64, error)

	// GetMatrixSvcsFunc mocks the GetMatrixSvcs method.
	GetMatrixSvcsFunc func() ([]MatrixSvcData, error)

	// GetOptimizerMasterFunc mocks the GetOptimizerMaster method.
	GetOptimizerMasterFunc func() (uint64, error)

	// GetOptimizerMatricesFunc mocks the GetOptimizerMatrices method.
	GetOptimizerMatricesFunc func() ([]Matrix, error)

	// UpdateLiveMatrixFunc mocks the UpdateLiveMatrix method.
	UpdateLiveMatrixFunc func(matrixData []byte) error

	// UpdateMatrixSvcFunc mocks the UpdateMatrixSvc method.
	UpdateMatrixSvcFunc func(matrixSvcData MatrixSvcData) error

	// UpdateMatrixSvcMasterFunc mocks the UpdateMatrixSvcMaster method.
	UpdateMatrixSvcMasterFunc func(id uint64) error

	// UpdateOptimizerMasterFunc mocks the UpdateOptimizerMaster method.
	UpdateOptimizerMasterFunc func(id uint64) error

	// UpdateOptimizerMatrixFunc mocks the UpdateOptimizerMatrix method.
	UpdateOptimizerMatrixFunc func(matrix Matrix) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteMatrixSvc holds details about calls to the DeleteMatrixSvc method.
		DeleteMatrixSvc []struct {
			// ID is the id argument value.
			ID uint64
		}
		// DeleteOptimizerMatrix holds details about calls to the DeleteOptimizerMatrix method.
		DeleteOptimizerMatrix []struct {
			// ID is the id argument value.
			ID uint64
		}
		// GetLiveMatrix holds details about calls to the GetLiveMatrix method.
		GetLiveMatrix []struct {
		}
		// GetMatrixSvcMaster holds details about calls to the GetMatrixSvcMaster method.
		GetMatrixSvcMaster []struct {
		}
		// GetMatrixSvcs holds details about calls to the GetMatrixSvcs method.
		GetMatrixSvcs []struct {
		}
		// GetOptimizerMaster holds details about calls to the GetOptimizerMaster method.
		GetOptimizerMaster []struct {
		}
		// GetOptimizerMatrices holds details about calls to the GetOptimizerMatrices method.
		GetOptimizerMatrices []struct {
		}
		// UpdateLiveMatrix holds details about calls to the UpdateLiveMatrix method.
		UpdateLiveMatrix []struct {
			// MatrixData is the matrixData argument value.
			MatrixData []byte
		}
		// UpdateMatrixSvc holds details about calls to the UpdateMatrixSvc method.
		UpdateMatrixSvc []struct {
			// MatrixSvcData is the matrixSvcData argument value.
			MatrixSvcData MatrixSvcData
		}
		// UpdateMatrixSvcMaster holds details about calls to the UpdateMatrixSvcMaster method.
		UpdateMatrixSvcMaster []struct {
			// ID is the id argument value.
			ID uint64
		}
		// UpdateOptimizerMaster holds details about calls to the UpdateOptimizerMaster method.
		UpdateOptimizerMaster []struct {
			// ID is the id argument value.
			ID uint64
		}
		// UpdateOptimizerMatrix holds details about calls to the UpdateOptimizerMatrix method.
		UpdateOptimizerMatrix []struct {
			// Matrix is the matrix argument value.
			Matrix Matrix
		}
	}
}

// DeleteMatrixSvc calls DeleteMatrixSvcFunc.
func (mock *MatrixStoreMock) DeleteMatrixSvc(id uint64) error {
	if mock.DeleteMatrixSvcFunc == nil {
		panic("MatrixStoreMock.DeleteMatrixSvcFunc: method is nil but MatrixStore.DeleteMatrixSvc was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	lockMatrixStoreMockDeleteMatrixSvc.Lock()
	mock.calls.DeleteMatrixSvc = append(mock.calls.DeleteMatrixSvc, callInfo)
	lockMatrixStoreMockDeleteMatrixSvc.Unlock()
	return mock.DeleteMatrixSvcFunc(id)
}

// DeleteMatrixSvcCalls gets all the calls that were made to DeleteMatrixSvc.
// Check the length with:
//     len(mockedMatrixStore.DeleteMatrixSvcCalls())
func (mock *MatrixStoreMock) DeleteMatrixSvcCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	lockMatrixStoreMockDeleteMatrixSvc.RLock()
	calls = mock.calls.DeleteMatrixSvc
	lockMatrixStoreMockDeleteMatrixSvc.RUnlock()
	return calls
}

// DeleteOptimizerMatrix calls DeleteOptimizerMatrixFunc.
func (mock *MatrixStoreMock) DeleteOptimizerMatrix(id uint64) error {
	if mock.DeleteOptimizerMatrixFunc == nil {
		panic("MatrixStoreMock.DeleteOptimizerMatrixFunc: method is nil but MatrixStore.DeleteOptimizerMatrix was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	lockMatrixStoreMockDeleteOptimizerMatrix.Lock()
	mock.calls.DeleteOptimizerMatrix = append(mock.calls.DeleteOptimizerMatrix, callInfo)
	lockMatrixStoreMockDeleteOptimizerMatrix.Unlock()
	return mock.DeleteOptimizerMatrixFunc(id)
}

// DeleteOptimizerMatrixCalls gets all the calls that were made to DeleteOptimizerMatrix.
// Check the length with:
//     len(mockedMatrixStore.DeleteOptimizerMatrixCalls())
func (mock *MatrixStoreMock) DeleteOptimizerMatrixCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	lockMatrixStoreMockDeleteOptimizerMatrix.RLock()
	calls = mock.calls.DeleteOptimizerMatrix
	lockMatrixStoreMockDeleteOptimizerMatrix.RUnlock()
	return calls
}

// GetLiveMatrix calls GetLiveMatrixFunc.
func (mock *MatrixStoreMock) GetLiveMatrix() ([]byte, error) {
	if mock.GetLiveMatrixFunc == nil {
		panic("MatrixStoreMock.GetLiveMatrixFunc: method is nil but MatrixStore.GetLiveMatrix was just called")
	}
	callInfo := struct {
	}{}
	lockMatrixStoreMockGetLiveMatrix.Lock()
	mock.calls.GetLiveMatrix = append(mock.calls.GetLiveMatrix, callInfo)
	lockMatrixStoreMockGetLiveMatrix.Unlock()
	return mock.GetLiveMatrixFunc()
}

// GetLiveMatrixCalls gets all the calls that were made to GetLiveMatrix.
// Check the length with:
//     len(mockedMatrixStore.GetLiveMatrixCalls())
func (mock *MatrixStoreMock) GetLiveMatrixCalls() []struct {
} {
	var calls []struct {
	}
	lockMatrixStoreMockGetLiveMatrix.RLock()
	calls = mock.calls.GetLiveMatrix
	lockMatrixStoreMockGetLiveMatrix.RUnlock()
	return calls
}

// GetMatrixSvcMaster calls GetMatrixSvcMasterFunc.
func (mock *MatrixStoreMock) GetMatrixSvcMaster() (uint64, error) {
	if mock.GetMatrixSvcMasterFunc == nil {
		panic("MatrixStoreMock.GetMatrixSvcMasterFunc: method is nil but MatrixStore.GetMatrixSvcMaster was just called")
	}
	callInfo := struct {
	}{}
	lockMatrixStoreMockGetMatrixSvcMaster.Lock()
	mock.calls.GetMatrixSvcMaster = append(mock.calls.GetMatrixSvcMaster, callInfo)
	lockMatrixStoreMockGetMatrixSvcMaster.Unlock()
	return mock.GetMatrixSvcMasterFunc()
}

// GetMatrixSvcMasterCalls gets all the calls that were made to GetMatrixSvcMaster.
// Check the length with:
//     len(mockedMatrixStore.GetMatrixSvcMasterCalls())
func (mock *MatrixStoreMock) GetMatrixSvcMasterCalls() []struct {
} {
	var calls []struct {
	}
	lockMatrixStoreMockGetMatrixSvcMaster.RLock()
	calls = mock.calls.GetMatrixSvcMaster
	lockMatrixStoreMockGetMatrixSvcMaster.RUnlock()
	return calls
}

// GetMatrixSvcs calls GetMatrixSvcsFunc.
func (mock *MatrixStoreMock) GetMatrixSvcs() ([]MatrixSvcData, error) {
	if mock.GetMatrixSvcsFunc == nil {
		panic("MatrixStoreMock.GetMatrixSvcsFunc: method is nil but MatrixStore.GetMatrixSvcs was just called")
	}
	callInfo := struct {
	}{}
	lockMatrixStoreMockGetMatrixSvcs.Lock()
	mock.calls.GetMatrixSvcs = append(mock.calls.GetMatrixSvcs, callInfo)
	lockMatrixStoreMockGetMatrixSvcs.Unlock()
	return mock.GetMatrixSvcsFunc()
}

// GetMatrixSvcsCalls gets all the calls that were made to GetMatrixSvcs.
// Check the length with:
//     len(mockedMatrixStore.GetMatrixSvcsCalls())
func (mock *MatrixStoreMock) GetMatrixSvcsCalls() []struct {
} {
	var calls []struct {
	}
	lockMatrixStoreMockGetMatrixSvcs.RLock()
	calls = mock.calls.GetMatrixSvcs
	lockMatrixStoreMockGetMatrixSvcs.RUnlock()
	return calls
}

// GetOptimizerMaster calls GetOptimizerMasterFunc.
func (mock *MatrixStoreMock) GetOptimizerMaster() (uint64, error) {
	if mock.GetOptimizerMasterFunc == nil {
		panic("MatrixStoreMock.GetOptimizerMasterFunc: method is nil but MatrixStore.GetOptimizerMaster was just called")
	}
	callInfo := struct {
	}{}
	lockMatrixStoreMockGetOptimizerMaster.Lock()
	mock.calls.GetOptimizerMaster = append(mock.calls.GetOptimizerMaster, callInfo)
	lockMatrixStoreMockGetOptimizerMaster.Unlock()
	return mock.GetOptimizerMasterFunc()
}

// GetOptimizerMasterCalls gets all the calls that were made to GetOptimizerMaster.
// Check the length with:
//     len(mockedMatrixStore.GetOptimizerMasterCalls())
func (mock *MatrixStoreMock) GetOptimizerMasterCalls() []struct {
} {
	var calls []struct {
	}
	lockMatrixStoreMockGetOptimizerMaster.RLock()
	calls = mock.calls.GetOptimizerMaster
	lockMatrixStoreMockGetOptimizerMaster.RUnlock()
	return calls
}

// GetOptimizerMatrices calls GetOptimizerMatricesFunc.
func (mock *MatrixStoreMock) GetOptimizerMatrices() ([]Matrix, error) {
	if mock.GetOptimizerMatricesFunc == nil {
		panic("MatrixStoreMock.GetOptimizerMatricesFunc: method is nil but MatrixStore.GetOptimizerMatrices was just called")
	}
	callInfo := struct {
	}{}
	lockMatrixStoreMockGetOptimizerMatrices.Lock()
	mock.calls.GetOptimizerMatrices = append(mock.calls.GetOptimizerMatrices, callInfo)
	lockMatrixStoreMockGetOptimizerMatrices.Unlock()
	return mock.GetOptimizerMatricesFunc()
}

// GetOptimizerMatricesCalls gets all the calls that were made to GetOptimizerMatrices.
// Check the length with:
//     len(mockedMatrixStore.GetOptimizerMatricesCalls())
func (mock *MatrixStoreMock) GetOptimizerMatricesCalls() []struct {
} {
	var calls []struct {
	}
	lockMatrixStoreMockGetOptimizerMatrices.RLock()
	calls = mock.calls.GetOptimizerMatrices
	lockMatrixStoreMockGetOptimizerMatrices.RUnlock()
	return calls
}

// UpdateLiveMatrix calls UpdateLiveMatrixFunc.
func (mock *MatrixStoreMock) UpdateLiveMatrix(matrixData []byte) error {
	if mock.UpdateLiveMatrixFunc == nil {
		panic("MatrixStoreMock.UpdateLiveMatrixFunc: method is nil but MatrixStore.UpdateLiveMatrix was just called")
	}
	callInfo := struct {
		MatrixData []byte
	}{
		MatrixData: matrixData,
	}
	lockMatrixStoreMockUpdateLiveMatrix.Lock()
	mock.calls.UpdateLiveMatrix = append(mock.calls.UpdateLiveMatrix, callInfo)
	lockMatrixStoreMockUpdateLiveMatrix.Unlock()
	return mock.UpdateLiveMatrixFunc(matrixData)
}

// UpdateLiveMatrixCalls gets all the calls that were made to UpdateLiveMatrix.
// Check the length with:
//     len(mockedMatrixStore.UpdateLiveMatrixCalls())
func (mock *MatrixStoreMock) UpdateLiveMatrixCalls() []struct {
	MatrixData []byte
} {
	var calls []struct {
		MatrixData []byte
	}
	lockMatrixStoreMockUpdateLiveMatrix.RLock()
	calls = mock.calls.UpdateLiveMatrix
	lockMatrixStoreMockUpdateLiveMatrix.RUnlock()
	return calls
}

// UpdateMatrixSvc calls UpdateMatrixSvcFunc.
func (mock *MatrixStoreMock) UpdateMatrixSvc(matrixSvcData MatrixSvcData) error {
	if mock.UpdateMatrixSvcFunc == nil {
		panic("MatrixStoreMock.UpdateMatrixSvcFunc: method is nil but MatrixStore.UpdateMatrixSvc was just called")
	}
	callInfo := struct {
		MatrixSvcData MatrixSvcData
	}{
		MatrixSvcData: matrixSvcData,
	}
	lockMatrixStoreMockUpdateMatrixSvc.Lock()
	mock.calls.UpdateMatrixSvc = append(mock.calls.UpdateMatrixSvc, callInfo)
	lockMatrixStoreMockUpdateMatrixSvc.Unlock()
	return mock.UpdateMatrixSvcFunc(matrixSvcData)
}

// UpdateMatrixSvcCalls gets all the calls that were made to UpdateMatrixSvc.
// Check the length with:
//     len(mockedMatrixStore.UpdateMatrixSvcCalls())
func (mock *MatrixStoreMock) UpdateMatrixSvcCalls() []struct {
	MatrixSvcData MatrixSvcData
} {
	var calls []struct {
		MatrixSvcData MatrixSvcData
	}
	lockMatrixStoreMockUpdateMatrixSvc.RLock()
	calls = mock.calls.UpdateMatrixSvc
	lockMatrixStoreMockUpdateMatrixSvc.RUnlock()
	return calls
}

// UpdateMatrixSvcMaster calls UpdateMatrixSvcMasterFunc.
func (mock *MatrixStoreMock) UpdateMatrixSvcMaster(id uint64) error {
	if mock.UpdateMatrixSvcMasterFunc == nil {
		panic("MatrixStoreMock.UpdateMatrixSvcMasterFunc: method is nil but MatrixStore.UpdateMatrixSvcMaster was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	lockMatrixStoreMockUpdateMatrixSvcMaster.Lock()
	mock.calls.UpdateMatrixSvcMaster = append(mock.calls.UpdateMatrixSvcMaster, callInfo)
	lockMatrixStoreMockUpdateMatrixSvcMaster.Unlock()
	return mock.UpdateMatrixSvcMasterFunc(id)
}

// UpdateMatrixSvcMasterCalls gets all the calls that were made to UpdateMatrixSvcMaster.
// Check the length with:
//     len(mockedMatrixStore.UpdateMatrixSvcMasterCalls())
func (mock *MatrixStoreMock) UpdateMatrixSvcMasterCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	lockMatrixStoreMockUpdateMatrixSvcMaster.RLock()
	calls = mock.calls.UpdateMatrixSvcMaster
	lockMatrixStoreMockUpdateMatrixSvcMaster.RUnlock()
	return calls
}

// UpdateOptimizerMaster calls UpdateOptimizerMasterFunc.
func (mock *MatrixStoreMock) UpdateOptimizerMaster(id uint64) error {
	if mock.UpdateOptimizerMasterFunc == nil {
		panic("MatrixStoreMock.UpdateOptimizerMasterFunc: method is nil but MatrixStore.UpdateOptimizerMaster was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	lockMatrixStoreMockUpdateOptimizerMaster.Lock()
	mock.calls.UpdateOptimizerMaster = append(mock.calls.UpdateOptimizerMaster, callInfo)
	lockMatrixStoreMockUpdateOptimizerMaster.Unlock()
	return mock.UpdateOptimizerMasterFunc(id)
}

// UpdateOptimizerMasterCalls gets all the calls that were made to UpdateOptimizerMaster.
// Check the length with:
//     len(mockedMatrixStore.UpdateOptimizerMasterCalls())
func (mock *MatrixStoreMock) UpdateOptimizerMasterCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	lockMatrixStoreMockUpdateOptimizerMaster.RLock()
	calls = mock.calls.UpdateOptimizerMaster
	lockMatrixStoreMockUpdateOptimizerMaster.RUnlock()
	return calls
}

// UpdateOptimizerMatrix calls UpdateOptimizerMatrixFunc.
func (mock *MatrixStoreMock) UpdateOptimizerMatrix(matrix Matrix) error {
	if mock.UpdateOptimizerMatrixFunc == nil {
		panic("MatrixStoreMock.UpdateOptimizerMatrixFunc: method is nil but MatrixStore.UpdateOptimizerMatrix was just called")
	}
	callInfo := struct {
		Matrix Matrix
	}{
		Matrix: matrix,
	}
	lockMatrixStoreMockUpdateOptimizerMatrix.Lock()
	mock.calls.UpdateOptimizerMatrix = append(mock.calls.UpdateOptimizerMatrix, callInfo)
	lockMatrixStoreMockUpdateOptimizerMatrix.Unlock()
	return mock.UpdateOptimizerMatrixFunc(matrix)
}

// UpdateOptimizerMatrixCalls gets all the calls that were made to UpdateOptimizerMatrix.
// Check the length with:
//     len(mockedMatrixStore.UpdateOptimizerMatrixCalls())
func (mock *MatrixStoreMock) UpdateOptimizerMatrixCalls() []struct {
	Matrix Matrix
} {
	var calls []struct {
		Matrix Matrix
	}
	lockMatrixStoreMockUpdateOptimizerMatrix.RLock()
	calls = mock.calls.UpdateOptimizerMatrix
	lockMatrixStoreMockUpdateOptimizerMatrix.RUnlock()
	return calls
}
