/*
    Network Next SDK. Copyright © 2017 - 2020 Network Next, Inc.

	Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
	conditions are met:

	1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

	2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
	   and the following disclaimer in the documentation and/or other materials provided with the distribution.

	3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
	   products derived from this software without specific prior written permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
	IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
	CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
	OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
	NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#pragma once

#if defined(NETWORKNEXT_UNREAL_ENGINE_416)
#define NETWORKNEXT_INCLUDE_NEXT_H_WITH_SHORT_PATH
#define NETWORKNEXT_INCLUDE_WORLD_H_WITH_SHORT_PATH
#define NETWORKNEXT_INCLUDE_IP_ADDRESS_HEADER_IN_UTILS
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_HASPENDINGCONNECTION
#define NETWORKNEXT_SOCKETSUBSYSTEM_INTERFACE_HAS_FORCEUDP
#elif defined(NETWORKNEXT_UNREAL_ENGINE_422)
#define NETWORKNEXT_INCLUDE_ENGINE_BASE_TYPES_IN_NETDRIVER
#define NETWORKNEXT_HAS_ESOCKETPROTOCOLFAMILY
#define NETWORKNEXT_SUPPORTS_GETINTERNETADDR_ON_CONNECTION
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_SHUTDOWN
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_WAITFORPENDINGCONNECTION
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_JOINMULTICASTGROUP_INTERFACEADDR_OVERLOAD
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_LEAVEMULTICASTGROUP_INTERFACEADDR_OVERLOAD
#define NETWORKNEXT_SOCKET_INTERFACE_HAS_SETMULTICASTINTERFACE
#define NETWORKNEXT_SOCKETSUBSYSTEM_INTERFACE_HAS_PROTOCOLTYPE
#define NETWORKNEXT_SOCKETSUBSYSTEM_INTERFACE_HAS_GETADDRESSINFO
#define NETWORKNEXT_SOCKETSUBSYSTEM_INTERFACE_HAS_ISSOCKETWAITSUPPORTED
#else
#error Unsupported Unreal Engine 4 version.
#endif