# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = bin
  TARGET = $(TARGETDIR)/libsodium.a
  OBJDIR = obj/Debug/sodium
  DEFINES += -D_DEBUG -DSODIUM_STATIC -DSODIUM_EXPORT= -DCONFIGURED=1
  INCLUDES += -Isodium/include/sodium
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Werror -ffast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unknown-pragmas -Wno-unused-variable -Wno-type-limits
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Werror -ffast-math -g -Wall -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Wno-unknown-pragmas -Wno-unused-variable -Wno-type-limits
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = bin
  TARGET = $(TARGETDIR)/libsodium.a
  OBJDIR = obj/Release/sodium
  DEFINES += -DNDEBUG -DSODIUM_STATIC -DSODIUM_EXPORT= -DCONFIGURED=1
  INCLUDES += -Isodium/include/sodium
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Werror -ffast-math -O3 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unknown-pragmas -Wno-unused-variable -Wno-type-limits
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Werror -ffast-math -O3 -g -Wall -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Wno-unknown-pragmas -Wno-unused-variable -Wno-type-limits
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/aead_aes256gcm_aesni.o \
	$(OBJDIR)/aead_chacha20poly1305.o \
	$(OBJDIR)/aead_xchacha20poly1305.o \
	$(OBJDIR)/crypto_auth.o \
	$(OBJDIR)/auth_hmacsha256.o \
	$(OBJDIR)/auth_hmacsha512.o \
	$(OBJDIR)/auth_hmacsha512256.o \
	$(OBJDIR)/crypto_box.o \
	$(OBJDIR)/crypto_box_easy.o \
	$(OBJDIR)/crypto_box_seal.o \
	$(OBJDIR)/box_curve25519xchacha20poly1305.o \
	$(OBJDIR)/box_seal_curve25519xchacha20poly1305.o \
	$(OBJDIR)/box_curve25519xsalsa20poly1305.o \
	$(OBJDIR)/core_ed25519.o \
	$(OBJDIR)/ed25519_ref10.o \
	$(OBJDIR)/core_hchacha20.o \
	$(OBJDIR)/core_hsalsa20.o \
	$(OBJDIR)/core_hsalsa20_ref2.o \
	$(OBJDIR)/core_salsa_ref.o \
	$(OBJDIR)/generichash_blake2.o \
	$(OBJDIR)/blake2b-compress-avx2.o \
	$(OBJDIR)/blake2b-compress-ref.o \
	$(OBJDIR)/blake2b-compress-sse41.o \
	$(OBJDIR)/blake2b-compress-ssse3.o \
	$(OBJDIR)/blake2b-ref.o \
	$(OBJDIR)/generichash_blake2b.o \
	$(OBJDIR)/crypto_generichash.o \
	$(OBJDIR)/crypto_hash.o \
	$(OBJDIR)/hash_sha256_cp.o \
	$(OBJDIR)/hash_sha256.o \
	$(OBJDIR)/hash_sha512_cp.o \
	$(OBJDIR)/hash_sha512.o \
	$(OBJDIR)/kdf_blake2b.o \
	$(OBJDIR)/crypto_kdf.o \
	$(OBJDIR)/crypto_kx.o \
	$(OBJDIR)/crypto_onetimeauth.o \
	$(OBJDIR)/poly1305_donna.o \
	$(OBJDIR)/onetimeauth_poly1305.o \
	$(OBJDIR)/poly1305_sse2.o \
	$(OBJDIR)/argon2-core.o \
	$(OBJDIR)/argon2-encoding.o \
	$(OBJDIR)/argon2-fill-block-avx2.o \
	$(OBJDIR)/argon2-fill-block-avx512f.o \
	$(OBJDIR)/argon2-fill-block-ref.o \
	$(OBJDIR)/argon2-fill-block-ssse3.o \
	$(OBJDIR)/argon2.o \
	$(OBJDIR)/blake2b-long.o \
	$(OBJDIR)/pwhash_argon2i.o \
	$(OBJDIR)/pwhash_argon2id.o \
	$(OBJDIR)/crypto_pwhash.o \
	$(OBJDIR)/crypto_scrypt-common.o \
	$(OBJDIR)/pwhash_scryptsalsa208sha256_nosse.o \
	$(OBJDIR)/pbkdf2-sha256.o \
	$(OBJDIR)/pwhash_scryptsalsa208sha256.o \
	$(OBJDIR)/scrypt_platform.o \
	$(OBJDIR)/pwhash_scryptsalsa208sha256_sse.o \
	$(OBJDIR)/crypto_scalarmult.o \
	$(OBJDIR)/x25519_ref10.o \
	$(OBJDIR)/curve25519_sandy2x.o \
	$(OBJDIR)/fe51_invert.o \
	$(OBJDIR)/fe_frombytes_sandy2x.o \
	$(OBJDIR)/scalarmult_curve25519.o \
	$(OBJDIR)/scalarmult_ed25519_ref10.o \
	$(OBJDIR)/crypto_secretbox.o \
	$(OBJDIR)/crypto_secretbox_easy.o \
	$(OBJDIR)/secretbox_xchacha20poly1305.o \
	$(OBJDIR)/secretbox_xsalsa20poly1305.o \
	$(OBJDIR)/secretstream_xchacha20poly1305.o \
	$(OBJDIR)/crypto_shorthash.o \
	$(OBJDIR)/shorthash_siphash24_ref.o \
	$(OBJDIR)/shorthash_siphashx24_ref.o \
	$(OBJDIR)/shorthash_siphash24.o \
	$(OBJDIR)/shorthash_siphashx24.o \
	$(OBJDIR)/crypto_sign.o \
	$(OBJDIR)/keypair.o \
	$(OBJDIR)/obsolete.o \
	$(OBJDIR)/open.o \
	$(OBJDIR)/sign.o \
	$(OBJDIR)/sign_ed25519.o \
	$(OBJDIR)/chacha20_dolbeau-avx2.o \
	$(OBJDIR)/chacha20_dolbeau-ssse3.o \
	$(OBJDIR)/chacha20_ref.o \
	$(OBJDIR)/stream_chacha20.o \
	$(OBJDIR)/crypto_stream.o \
	$(OBJDIR)/salsa20_ref.o \
	$(OBJDIR)/stream_salsa20.o \
	$(OBJDIR)/salsa20_xmm6.o \
	$(OBJDIR)/salsa20_xmm6int-avx2.o \
	$(OBJDIR)/salsa20_xmm6int-sse2.o \
	$(OBJDIR)/stream_salsa2012_ref.o \
	$(OBJDIR)/stream_salsa2012.o \
	$(OBJDIR)/stream_salsa208_ref.o \
	$(OBJDIR)/stream_salsa208.o \
	$(OBJDIR)/stream_xchacha20.o \
	$(OBJDIR)/stream_xsalsa20.o \
	$(OBJDIR)/verify.o \
	$(OBJDIR)/randombytes_nativeclient.o \
	$(OBJDIR)/randombytes.o \
	$(OBJDIR)/randombytes_salsa20_random.o \
	$(OBJDIR)/randombytes_sysrandom.o \
	$(OBJDIR)/codecs.o \
	$(OBJDIR)/core.o \
	$(OBJDIR)/runtime.o \
	$(OBJDIR)/utils.o \
	$(OBJDIR)/version.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking sodium
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning sodium
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/aead_aes256gcm_aesni.o: sodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/aead_chacha20poly1305.o: sodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/aead_xchacha20poly1305.o: sodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_auth.o: sodium/crypto_auth/crypto_auth.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/auth_hmacsha256.o: sodium/crypto_auth/hmacsha256/auth_hmacsha256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/auth_hmacsha512.o: sodium/crypto_auth/hmacsha512/auth_hmacsha512.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/auth_hmacsha512256.o: sodium/crypto_auth/hmacsha512256/auth_hmacsha512256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_box.o: sodium/crypto_box/crypto_box.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_box_easy.o: sodium/crypto_box/crypto_box_easy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_box_seal.o: sodium/crypto_box/crypto_box_seal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/box_curve25519xchacha20poly1305.o: sodium/crypto_box/curve25519xchacha20poly1305/box_curve25519xchacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/box_seal_curve25519xchacha20poly1305.o: sodium/crypto_box/curve25519xchacha20poly1305/box_seal_curve25519xchacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/box_curve25519xsalsa20poly1305.o: sodium/crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_ed25519.o: sodium/crypto_core/ed25519/core_ed25519.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ed25519_ref10.o: sodium/crypto_core/ed25519/ref10/ed25519_ref10.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_hchacha20.o: sodium/crypto_core/hchacha20/core_hchacha20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_hsalsa20.o: sodium/crypto_core/hsalsa20/core_hsalsa20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_hsalsa20_ref2.o: sodium/crypto_core/hsalsa20/ref2/core_hsalsa20_ref2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_salsa_ref.o: sodium/crypto_core/salsa/ref/core_salsa_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/generichash_blake2.o: sodium/crypto_generichash/blake2b/generichash_blake2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-compress-avx2.o: sodium/crypto_generichash/blake2b/ref/blake2b-compress-avx2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-compress-ref.o: sodium/crypto_generichash/blake2b/ref/blake2b-compress-ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-compress-sse41.o: sodium/crypto_generichash/blake2b/ref/blake2b-compress-sse41.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-compress-ssse3.o: sodium/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-ref.o: sodium/crypto_generichash/blake2b/ref/blake2b-ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/generichash_blake2b.o: sodium/crypto_generichash/blake2b/ref/generichash_blake2b.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_generichash.o: sodium/crypto_generichash/crypto_generichash.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_hash.o: sodium/crypto_hash/crypto_hash.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hash_sha256_cp.o: sodium/crypto_hash/sha256/cp/hash_sha256_cp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hash_sha256.o: sodium/crypto_hash/sha256/hash_sha256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hash_sha512_cp.o: sodium/crypto_hash/sha512/cp/hash_sha512_cp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hash_sha512.o: sodium/crypto_hash/sha512/hash_sha512.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/kdf_blake2b.o: sodium/crypto_kdf/blake2b/kdf_blake2b.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_kdf.o: sodium/crypto_kdf/crypto_kdf.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_kx.o: sodium/crypto_kx/crypto_kx.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_onetimeauth.o: sodium/crypto_onetimeauth/crypto_onetimeauth.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/poly1305_donna.o: sodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/onetimeauth_poly1305.o: sodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/poly1305_sse2.o: sodium/crypto_onetimeauth/poly1305/sse2/poly1305_sse2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-core.o: sodium/crypto_pwhash/argon2/argon2-core.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-encoding.o: sodium/crypto_pwhash/argon2/argon2-encoding.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-fill-block-avx2.o: sodium/crypto_pwhash/argon2/argon2-fill-block-avx2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-fill-block-avx512f.o: sodium/crypto_pwhash/argon2/argon2-fill-block-avx512f.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-fill-block-ref.o: sodium/crypto_pwhash/argon2/argon2-fill-block-ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2-fill-block-ssse3.o: sodium/crypto_pwhash/argon2/argon2-fill-block-ssse3.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/argon2.o: sodium/crypto_pwhash/argon2/argon2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/blake2b-long.o: sodium/crypto_pwhash/argon2/blake2b-long.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pwhash_argon2i.o: sodium/crypto_pwhash/argon2/pwhash_argon2i.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pwhash_argon2id.o: sodium/crypto_pwhash/argon2/pwhash_argon2id.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_pwhash.o: sodium/crypto_pwhash/crypto_pwhash.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_scrypt-common.o: sodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt-common.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pwhash_scryptsalsa208sha256_nosse.o: sodium/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pbkdf2-sha256.o: sodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pwhash_scryptsalsa208sha256.o: sodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scrypt_platform.o: sodium/crypto_pwhash/scryptsalsa208sha256/scrypt_platform.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pwhash_scryptsalsa208sha256_sse.o: sodium/crypto_pwhash/scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_scalarmult.o: sodium/crypto_scalarmult/crypto_scalarmult.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/x25519_ref10.o: sodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/curve25519_sandy2x.o: sodium/crypto_scalarmult/curve25519/sandy2x/curve25519_sandy2x.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fe51_invert.o: sodium/crypto_scalarmult/curve25519/sandy2x/fe51_invert.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fe_frombytes_sandy2x.o: sodium/crypto_scalarmult/curve25519/sandy2x/fe_frombytes_sandy2x.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scalarmult_curve25519.o: sodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scalarmult_ed25519_ref10.o: sodium/crypto_scalarmult/ed25519/ref10/scalarmult_ed25519_ref10.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_secretbox.o: sodium/crypto_secretbox/crypto_secretbox.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_secretbox_easy.o: sodium/crypto_secretbox/crypto_secretbox_easy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/secretbox_xchacha20poly1305.o: sodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/secretbox_xsalsa20poly1305.o: sodium/crypto_secretbox/xsalsa20poly1305/secretbox_xsalsa20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/secretstream_xchacha20poly1305.o: sodium/crypto_secretstream/xchacha20poly1305/secretstream_xchacha20poly1305.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_shorthash.o: sodium/crypto_shorthash/crypto_shorthash.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shorthash_siphash24_ref.o: sodium/crypto_shorthash/siphash24/ref/shorthash_siphash24_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shorthash_siphashx24_ref.o: sodium/crypto_shorthash/siphash24/ref/shorthash_siphashx24_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shorthash_siphash24.o: sodium/crypto_shorthash/siphash24/shorthash_siphash24.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shorthash_siphashx24.o: sodium/crypto_shorthash/siphash24/shorthash_siphashx24.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_sign.o: sodium/crypto_sign/crypto_sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/keypair.o: sodium/crypto_sign/ed25519/ref10/keypair.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/obsolete.o: sodium/crypto_sign/ed25519/ref10/obsolete.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/open.o: sodium/crypto_sign/ed25519/ref10/open.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sign.o: sodium/crypto_sign/ed25519/ref10/sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sign_ed25519.o: sodium/crypto_sign/ed25519/sign_ed25519.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chacha20_dolbeau-avx2.o: sodium/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-avx2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chacha20_dolbeau-ssse3.o: sodium/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-ssse3.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chacha20_ref.o: sodium/crypto_stream/chacha20/ref/chacha20_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_chacha20.o: sodium/crypto_stream/chacha20/stream_chacha20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypto_stream.o: sodium/crypto_stream/crypto_stream.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/salsa20_ref.o: sodium/crypto_stream/salsa20/ref/salsa20_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_salsa20.o: sodium/crypto_stream/salsa20/stream_salsa20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/salsa20_xmm6.o: sodium/crypto_stream/salsa20/xmm6/salsa20_xmm6.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/salsa20_xmm6int-avx2.o: sodium/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-avx2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/salsa20_xmm6int-sse2.o: sodium/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-sse2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_salsa2012_ref.o: sodium/crypto_stream/salsa2012/ref/stream_salsa2012_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_salsa2012.o: sodium/crypto_stream/salsa2012/stream_salsa2012.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_salsa208_ref.o: sodium/crypto_stream/salsa208/ref/stream_salsa208_ref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_salsa208.o: sodium/crypto_stream/salsa208/stream_salsa208.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_xchacha20.o: sodium/crypto_stream/xchacha20/stream_xchacha20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stream_xsalsa20.o: sodium/crypto_stream/xsalsa20/stream_xsalsa20.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/verify.o: sodium/crypto_verify/sodium/verify.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/randombytes_nativeclient.o: sodium/randombytes/nativeclient/randombytes_nativeclient.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/randombytes.o: sodium/randombytes/randombytes.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/randombytes_salsa20_random.o: sodium/randombytes/salsa20/randombytes_salsa20_random.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/randombytes_sysrandom.o: sodium/randombytes/sysrandom/randombytes_sysrandom.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/codecs.o: sodium/sodium/codecs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core.o: sodium/sodium/core.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/runtime.o: sodium/sodium/runtime.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: sodium/sodium/utils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/version.o: sodium/sodium/version.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif