version: '3'

services:
    redis:
        image: "redis:alpine"
        networks:
            - nn-net

    portal:
        build:
            context: ../
            dockerfile: ./cmd/portal/Dockerfile
        ports:
            - "20000:20000"
        depends_on:
            - redis
            - relay_backend
        networks:
            - nn-net
        environment:
            RELAY_PUBLIC_KEY: 9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
            RELAY_ROUTER_PRIVATE_KEY: ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=
            ROUTE_MATRIX_URI: http://relay_backend:30000/route_matrix
            BASIC_AUTH_USERNAME: local
            BASIC_AUTH_PASSWORD: local
            UI_DIR: ./cmd/portal/public
            PORT: 20000
    
    relay_backend:
        build:
            context: ../
            dockerfile: ./cmd/relay_backend/Dockerfile
        ports:
            - "30000:30000"
        depends_on:
            - redis
        networks:
            - nn-net
        environment:
            RELAY_PUBLIC_KEY: 9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
            RELAY_ROUTER_PRIVATE_KEY: ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=
            PORT: 30000

    server_backend:
        build:
            context: ../
            dockerfile: ./cmd/server_backend/Dockerfile
        ports:
            - "40000:40000/udp"
        depends_on:
            - redis
            - relay_backend
        networks:
            - nn-net
        environment:
            RELAY_PUBLIC_KEY: 9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
            RELAY_ROUTER_PRIVATE_KEY: ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=
            SERVER_BACKEND_PUBLIC_KEY: TGHKjEeHPtSgtZfDyuDPcQgtJTyRDtRvGSKvuiWWo0A=
            SERVER_BACKEND_PRIVATE_KEY: FXwFqzjGlIwUDwiq1N5Um5VUesdr4fP2hVV2cnJ+yARMYcqMR4c+1KC1l8PK4M9xCC0lPJEO1G8ZIq+6JZajQA==
            NEXT_CUSTOMER_PUBLIC_KEY: leN7D7+9vr24uT4f1Ba8PEEvIQA/UkGZLlT+sdeLRHKsVqaZq723Zw==
            ROUTE_MATRIX_URI: http://relay_backend:30000/route_matrix
            MAXMIND_DB_URI: /app/testdata/GeoIP2-City-Test.mmdb
            PORT: 40000

networks:
    nn-net:
        