// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: near/near.proto

package com.networknext.api.near;

public final class Near {
  private Near() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NearRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:near.NearRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float latitude = 1;</code>
     */
    float getLatitude();

    /**
     * <code>float longitude = 2;</code>
     */
    float getLongitude();

    /**
     * <code>uint32 maxRelays = 3;</code>
     */
    int getMaxRelays();

    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    java.util.List<com.networknext.api.id.Id.EntityId> 
        getExcludeList();
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    com.networknext.api.id.Id.EntityId getExclude(int index);
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    int getExcludeCount();
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    java.util.List<? extends com.networknext.api.id.Id.EntityIdOrBuilder> 
        getExcludeOrBuilderList();
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    com.networknext.api.id.Id.EntityIdOrBuilder getExcludeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code near.NearRequest}
   */
  public  static final class NearRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:near.NearRequest)
      NearRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NearRequest.newBuilder() to construct.
    private NearRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NearRequest() {
      latitude_ = 0F;
      longitude_ = 0F;
      maxRelays_ = 0;
      exclude_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NearRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              latitude_ = input.readFloat();
              break;
            }
            case 21: {

              longitude_ = input.readFloat();
              break;
            }
            case 24: {

              maxRelays_ = input.readUInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                exclude_ = new java.util.ArrayList<com.networknext.api.id.Id.EntityId>();
                mutable_bitField0_ |= 0x00000008;
              }
              exclude_.add(
                  input.readMessage(com.networknext.api.id.Id.EntityId.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          exclude_ = java.util.Collections.unmodifiableList(exclude_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.near.Near.internal_static_near_NearRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.near.Near.internal_static_near_NearRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.near.Near.NearRequest.class, com.networknext.api.near.Near.NearRequest.Builder.class);
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private float latitude_;
    /**
     * <code>float latitude = 1;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private float longitude_;
    /**
     * <code>float longitude = 2;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    public static final int MAXRELAYS_FIELD_NUMBER = 3;
    private int maxRelays_;
    /**
     * <code>uint32 maxRelays = 3;</code>
     */
    public int getMaxRelays() {
      return maxRelays_;
    }

    public static final int EXCLUDE_FIELD_NUMBER = 4;
    private java.util.List<com.networknext.api.id.Id.EntityId> exclude_;
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    public java.util.List<com.networknext.api.id.Id.EntityId> getExcludeList() {
      return exclude_;
    }
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    public java.util.List<? extends com.networknext.api.id.Id.EntityIdOrBuilder> 
        getExcludeOrBuilderList() {
      return exclude_;
    }
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    public int getExcludeCount() {
      return exclude_.size();
    }
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    public com.networknext.api.id.Id.EntityId getExclude(int index) {
      return exclude_.get(index);
    }
    /**
     * <code>repeated .id.EntityId exclude = 4;</code>
     */
    public com.networknext.api.id.Id.EntityIdOrBuilder getExcludeOrBuilder(
        int index) {
      return exclude_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0F) {
        output.writeFloat(1, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(2, longitude_);
      }
      if (maxRelays_ != 0) {
        output.writeUInt32(3, maxRelays_);
      }
      for (int i = 0; i < exclude_.size(); i++) {
        output.writeMessage(4, exclude_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, longitude_);
      }
      if (maxRelays_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, maxRelays_);
      }
      for (int i = 0; i < exclude_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exclude_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.near.Near.NearRequest)) {
        return super.equals(obj);
      }
      com.networknext.api.near.Near.NearRequest other = (com.networknext.api.near.Near.NearRequest) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getLatitude())
          == java.lang.Float.floatToIntBits(
              other.getLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getLongitude())
          == java.lang.Float.floatToIntBits(
              other.getLongitude()));
      result = result && (getMaxRelays()
          == other.getMaxRelays());
      result = result && getExcludeList()
          .equals(other.getExcludeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (37 * hash) + MAXRELAYS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxRelays();
      if (getExcludeCount() > 0) {
        hash = (37 * hash) + EXCLUDE_FIELD_NUMBER;
        hash = (53 * hash) + getExcludeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.near.Near.NearRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.near.Near.NearRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code near.NearRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:near.NearRequest)
        com.networknext.api.near.Near.NearRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.near.Near.internal_static_near_NearRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.near.Near.internal_static_near_NearRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.near.Near.NearRequest.class, com.networknext.api.near.Near.NearRequest.Builder.class);
      }

      // Construct using com.networknext.api.near.Near.NearRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExcludeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitude_ = 0F;

        longitude_ = 0F;

        maxRelays_ = 0;

        if (excludeBuilder_ == null) {
          exclude_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          excludeBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.near.Near.internal_static_near_NearRequest_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearRequest getDefaultInstanceForType() {
        return com.networknext.api.near.Near.NearRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearRequest build() {
        com.networknext.api.near.Near.NearRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearRequest buildPartial() {
        com.networknext.api.near.Near.NearRequest result = new com.networknext.api.near.Near.NearRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.maxRelays_ = maxRelays_;
        if (excludeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            exclude_ = java.util.Collections.unmodifiableList(exclude_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.exclude_ = exclude_;
        } else {
          result.exclude_ = excludeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.near.Near.NearRequest) {
          return mergeFrom((com.networknext.api.near.Near.NearRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.near.Near.NearRequest other) {
        if (other == com.networknext.api.near.Near.NearRequest.getDefaultInstance()) return this;
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        if (other.getMaxRelays() != 0) {
          setMaxRelays(other.getMaxRelays());
        }
        if (excludeBuilder_ == null) {
          if (!other.exclude_.isEmpty()) {
            if (exclude_.isEmpty()) {
              exclude_ = other.exclude_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureExcludeIsMutable();
              exclude_.addAll(other.exclude_);
            }
            onChanged();
          }
        } else {
          if (!other.exclude_.isEmpty()) {
            if (excludeBuilder_.isEmpty()) {
              excludeBuilder_.dispose();
              excludeBuilder_ = null;
              exclude_ = other.exclude_;
              bitField0_ = (bitField0_ & ~0x00000008);
              excludeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExcludeFieldBuilder() : null;
            } else {
              excludeBuilder_.addAllMessages(other.exclude_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.near.Near.NearRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.near.Near.NearRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float latitude_ ;
      /**
       * <code>float latitude = 1;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>float latitude = 1;</code>
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>float longitude = 2;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>float longitude = 2;</code>
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }

      private int maxRelays_ ;
      /**
       * <code>uint32 maxRelays = 3;</code>
       */
      public int getMaxRelays() {
        return maxRelays_;
      }
      /**
       * <code>uint32 maxRelays = 3;</code>
       */
      public Builder setMaxRelays(int value) {
        
        maxRelays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 maxRelays = 3;</code>
       */
      public Builder clearMaxRelays() {
        
        maxRelays_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.networknext.api.id.Id.EntityId> exclude_ =
        java.util.Collections.emptyList();
      private void ensureExcludeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          exclude_ = new java.util.ArrayList<com.networknext.api.id.Id.EntityId>(exclude_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> excludeBuilder_;

      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public java.util.List<com.networknext.api.id.Id.EntityId> getExcludeList() {
        if (excludeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exclude_);
        } else {
          return excludeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public int getExcludeCount() {
        if (excludeBuilder_ == null) {
          return exclude_.size();
        } else {
          return excludeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public com.networknext.api.id.Id.EntityId getExclude(int index) {
        if (excludeBuilder_ == null) {
          return exclude_.get(index);
        } else {
          return excludeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder setExclude(
          int index, com.networknext.api.id.Id.EntityId value) {
        if (excludeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExcludeIsMutable();
          exclude_.set(index, value);
          onChanged();
        } else {
          excludeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder setExclude(
          int index, com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (excludeBuilder_ == null) {
          ensureExcludeIsMutable();
          exclude_.set(index, builderForValue.build());
          onChanged();
        } else {
          excludeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder addExclude(com.networknext.api.id.Id.EntityId value) {
        if (excludeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExcludeIsMutable();
          exclude_.add(value);
          onChanged();
        } else {
          excludeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder addExclude(
          int index, com.networknext.api.id.Id.EntityId value) {
        if (excludeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExcludeIsMutable();
          exclude_.add(index, value);
          onChanged();
        } else {
          excludeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder addExclude(
          com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (excludeBuilder_ == null) {
          ensureExcludeIsMutable();
          exclude_.add(builderForValue.build());
          onChanged();
        } else {
          excludeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder addExclude(
          int index, com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (excludeBuilder_ == null) {
          ensureExcludeIsMutable();
          exclude_.add(index, builderForValue.build());
          onChanged();
        } else {
          excludeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder addAllExclude(
          java.lang.Iterable<? extends com.networknext.api.id.Id.EntityId> values) {
        if (excludeBuilder_ == null) {
          ensureExcludeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exclude_);
          onChanged();
        } else {
          excludeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder clearExclude() {
        if (excludeBuilder_ == null) {
          exclude_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          excludeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public Builder removeExclude(int index) {
        if (excludeBuilder_ == null) {
          ensureExcludeIsMutable();
          exclude_.remove(index);
          onChanged();
        } else {
          excludeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder getExcludeBuilder(
          int index) {
        return getExcludeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public com.networknext.api.id.Id.EntityIdOrBuilder getExcludeOrBuilder(
          int index) {
        if (excludeBuilder_ == null) {
          return exclude_.get(index);  } else {
          return excludeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public java.util.List<? extends com.networknext.api.id.Id.EntityIdOrBuilder> 
           getExcludeOrBuilderList() {
        if (excludeBuilder_ != null) {
          return excludeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exclude_);
        }
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder addExcludeBuilder() {
        return getExcludeFieldBuilder().addBuilder(
            com.networknext.api.id.Id.EntityId.getDefaultInstance());
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder addExcludeBuilder(
          int index) {
        return getExcludeFieldBuilder().addBuilder(
            index, com.networknext.api.id.Id.EntityId.getDefaultInstance());
      }
      /**
       * <code>repeated .id.EntityId exclude = 4;</code>
       */
      public java.util.List<com.networknext.api.id.Id.EntityId.Builder> 
           getExcludeBuilderList() {
        return getExcludeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> 
          getExcludeFieldBuilder() {
        if (excludeBuilder_ == null) {
          excludeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder>(
                  exclude_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          exclude_ = null;
        }
        return excludeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:near.NearRequest)
    }

    // @@protoc_insertion_point(class_scope:near.NearRequest)
    private static final com.networknext.api.near.Near.NearRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.near.Near.NearRequest();
    }

    public static com.networknext.api.near.Near.NearRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NearRequest>
        PARSER = new com.google.protobuf.AbstractParser<NearRequest>() {
      @java.lang.Override
      public NearRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NearRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NearRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NearRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.near.Near.NearRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NearResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:near.NearResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    java.util.List<com.networknext.api.near.Near.NearResponseRelay> 
        getRelaysList();
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    com.networknext.api.near.Near.NearResponseRelay getRelays(int index);
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    int getRelaysCount();
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    java.util.List<? extends com.networknext.api.near.Near.NearResponseRelayOrBuilder> 
        getRelaysOrBuilderList();
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    com.networknext.api.near.Near.NearResponseRelayOrBuilder getRelaysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code near.NearResponse}
   */
  public  static final class NearResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:near.NearResponse)
      NearResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NearResponse.newBuilder() to construct.
    private NearResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NearResponse() {
      relays_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NearResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                relays_ = new java.util.ArrayList<com.networknext.api.near.Near.NearResponseRelay>();
                mutable_bitField0_ |= 0x00000001;
              }
              relays_.add(
                  input.readMessage(com.networknext.api.near.Near.NearResponseRelay.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          relays_ = java.util.Collections.unmodifiableList(relays_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.near.Near.internal_static_near_NearResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.near.Near.internal_static_near_NearResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.near.Near.NearResponse.class, com.networknext.api.near.Near.NearResponse.Builder.class);
    }

    public static final int RELAYS_FIELD_NUMBER = 1;
    private java.util.List<com.networknext.api.near.Near.NearResponseRelay> relays_;
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    public java.util.List<com.networknext.api.near.Near.NearResponseRelay> getRelaysList() {
      return relays_;
    }
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    public java.util.List<? extends com.networknext.api.near.Near.NearResponseRelayOrBuilder> 
        getRelaysOrBuilderList() {
      return relays_;
    }
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    public int getRelaysCount() {
      return relays_.size();
    }
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    public com.networknext.api.near.Near.NearResponseRelay getRelays(int index) {
      return relays_.get(index);
    }
    /**
     * <code>repeated .near.NearResponseRelay relays = 1;</code>
     */
    public com.networknext.api.near.Near.NearResponseRelayOrBuilder getRelaysOrBuilder(
        int index) {
      return relays_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < relays_.size(); i++) {
        output.writeMessage(1, relays_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < relays_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, relays_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.near.Near.NearResponse)) {
        return super.equals(obj);
      }
      com.networknext.api.near.Near.NearResponse other = (com.networknext.api.near.Near.NearResponse) obj;

      boolean result = true;
      result = result && getRelaysList()
          .equals(other.getRelaysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRelaysCount() > 0) {
        hash = (37 * hash) + RELAYS_FIELD_NUMBER;
        hash = (53 * hash) + getRelaysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.near.Near.NearResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.near.Near.NearResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code near.NearResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:near.NearResponse)
        com.networknext.api.near.Near.NearResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.near.Near.internal_static_near_NearResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.near.Near.internal_static_near_NearResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.near.Near.NearResponse.class, com.networknext.api.near.Near.NearResponse.Builder.class);
      }

      // Construct using com.networknext.api.near.Near.NearResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRelaysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (relaysBuilder_ == null) {
          relays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          relaysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.near.Near.internal_static_near_NearResponse_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponse getDefaultInstanceForType() {
        return com.networknext.api.near.Near.NearResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponse build() {
        com.networknext.api.near.Near.NearResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponse buildPartial() {
        com.networknext.api.near.Near.NearResponse result = new com.networknext.api.near.Near.NearResponse(this);
        int from_bitField0_ = bitField0_;
        if (relaysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            relays_ = java.util.Collections.unmodifiableList(relays_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.relays_ = relays_;
        } else {
          result.relays_ = relaysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.near.Near.NearResponse) {
          return mergeFrom((com.networknext.api.near.Near.NearResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.near.Near.NearResponse other) {
        if (other == com.networknext.api.near.Near.NearResponse.getDefaultInstance()) return this;
        if (relaysBuilder_ == null) {
          if (!other.relays_.isEmpty()) {
            if (relays_.isEmpty()) {
              relays_ = other.relays_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRelaysIsMutable();
              relays_.addAll(other.relays_);
            }
            onChanged();
          }
        } else {
          if (!other.relays_.isEmpty()) {
            if (relaysBuilder_.isEmpty()) {
              relaysBuilder_.dispose();
              relaysBuilder_ = null;
              relays_ = other.relays_;
              bitField0_ = (bitField0_ & ~0x00000001);
              relaysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRelaysFieldBuilder() : null;
            } else {
              relaysBuilder_.addAllMessages(other.relays_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.near.Near.NearResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.near.Near.NearResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.networknext.api.near.Near.NearResponseRelay> relays_ =
        java.util.Collections.emptyList();
      private void ensureRelaysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          relays_ = new java.util.ArrayList<com.networknext.api.near.Near.NearResponseRelay>(relays_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.networknext.api.near.Near.NearResponseRelay, com.networknext.api.near.Near.NearResponseRelay.Builder, com.networknext.api.near.Near.NearResponseRelayOrBuilder> relaysBuilder_;

      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public java.util.List<com.networknext.api.near.Near.NearResponseRelay> getRelaysList() {
        if (relaysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relays_);
        } else {
          return relaysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public int getRelaysCount() {
        if (relaysBuilder_ == null) {
          return relays_.size();
        } else {
          return relaysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public com.networknext.api.near.Near.NearResponseRelay getRelays(int index) {
        if (relaysBuilder_ == null) {
          return relays_.get(index);
        } else {
          return relaysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder setRelays(
          int index, com.networknext.api.near.Near.NearResponseRelay value) {
        if (relaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelaysIsMutable();
          relays_.set(index, value);
          onChanged();
        } else {
          relaysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder setRelays(
          int index, com.networknext.api.near.Near.NearResponseRelay.Builder builderForValue) {
        if (relaysBuilder_ == null) {
          ensureRelaysIsMutable();
          relays_.set(index, builderForValue.build());
          onChanged();
        } else {
          relaysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder addRelays(com.networknext.api.near.Near.NearResponseRelay value) {
        if (relaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelaysIsMutable();
          relays_.add(value);
          onChanged();
        } else {
          relaysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder addRelays(
          int index, com.networknext.api.near.Near.NearResponseRelay value) {
        if (relaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelaysIsMutable();
          relays_.add(index, value);
          onChanged();
        } else {
          relaysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder addRelays(
          com.networknext.api.near.Near.NearResponseRelay.Builder builderForValue) {
        if (relaysBuilder_ == null) {
          ensureRelaysIsMutable();
          relays_.add(builderForValue.build());
          onChanged();
        } else {
          relaysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder addRelays(
          int index, com.networknext.api.near.Near.NearResponseRelay.Builder builderForValue) {
        if (relaysBuilder_ == null) {
          ensureRelaysIsMutable();
          relays_.add(index, builderForValue.build());
          onChanged();
        } else {
          relaysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder addAllRelays(
          java.lang.Iterable<? extends com.networknext.api.near.Near.NearResponseRelay> values) {
        if (relaysBuilder_ == null) {
          ensureRelaysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, relays_);
          onChanged();
        } else {
          relaysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder clearRelays() {
        if (relaysBuilder_ == null) {
          relays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          relaysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public Builder removeRelays(int index) {
        if (relaysBuilder_ == null) {
          ensureRelaysIsMutable();
          relays_.remove(index);
          onChanged();
        } else {
          relaysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public com.networknext.api.near.Near.NearResponseRelay.Builder getRelaysBuilder(
          int index) {
        return getRelaysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public com.networknext.api.near.Near.NearResponseRelayOrBuilder getRelaysOrBuilder(
          int index) {
        if (relaysBuilder_ == null) {
          return relays_.get(index);  } else {
          return relaysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public java.util.List<? extends com.networknext.api.near.Near.NearResponseRelayOrBuilder> 
           getRelaysOrBuilderList() {
        if (relaysBuilder_ != null) {
          return relaysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relays_);
        }
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public com.networknext.api.near.Near.NearResponseRelay.Builder addRelaysBuilder() {
        return getRelaysFieldBuilder().addBuilder(
            com.networknext.api.near.Near.NearResponseRelay.getDefaultInstance());
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public com.networknext.api.near.Near.NearResponseRelay.Builder addRelaysBuilder(
          int index) {
        return getRelaysFieldBuilder().addBuilder(
            index, com.networknext.api.near.Near.NearResponseRelay.getDefaultInstance());
      }
      /**
       * <code>repeated .near.NearResponseRelay relays = 1;</code>
       */
      public java.util.List<com.networknext.api.near.Near.NearResponseRelay.Builder> 
           getRelaysBuilderList() {
        return getRelaysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.networknext.api.near.Near.NearResponseRelay, com.networknext.api.near.Near.NearResponseRelay.Builder, com.networknext.api.near.Near.NearResponseRelayOrBuilder> 
          getRelaysFieldBuilder() {
        if (relaysBuilder_ == null) {
          relaysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.networknext.api.near.Near.NearResponseRelay, com.networknext.api.near.Near.NearResponseRelay.Builder, com.networknext.api.near.Near.NearResponseRelayOrBuilder>(
                  relays_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          relays_ = null;
        }
        return relaysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:near.NearResponse)
    }

    // @@protoc_insertion_point(class_scope:near.NearResponse)
    private static final com.networknext.api.near.Near.NearResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.near.Near.NearResponse();
    }

    public static com.networknext.api.near.Near.NearResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NearResponse>
        PARSER = new com.google.protobuf.AbstractParser<NearResponse>() {
      @java.lang.Override
      public NearResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NearResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NearResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NearResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.near.Near.NearResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NearResponseRelayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:near.NearResponseRelay)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    boolean hasRelayId();
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    com.networknext.api.id.Id.EntityId getRelayId();
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder();

    /**
     * <code>bytes address = 2;</code>
     */
    com.google.protobuf.ByteString getAddress();
  }
  /**
   * Protobuf type {@code near.NearResponseRelay}
   */
  public  static final class NearResponseRelay extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:near.NearResponseRelay)
      NearResponseRelayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NearResponseRelay.newBuilder() to construct.
    private NearResponseRelay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NearResponseRelay() {
      address_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NearResponseRelay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.networknext.api.id.Id.EntityId.Builder subBuilder = null;
              if (relayId_ != null) {
                subBuilder = relayId_.toBuilder();
              }
              relayId_ = input.readMessage(com.networknext.api.id.Id.EntityId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relayId_);
                relayId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              address_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networknext.api.near.Near.internal_static_near_NearResponseRelay_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networknext.api.near.Near.internal_static_near_NearResponseRelay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.networknext.api.near.Near.NearResponseRelay.class, com.networknext.api.near.Near.NearResponseRelay.Builder.class);
    }

    public static final int RELAYID_FIELD_NUMBER = 1;
    private com.networknext.api.id.Id.EntityId relayId_;
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public boolean hasRelayId() {
      return relayId_ != null;
    }
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public com.networknext.api.id.Id.EntityId getRelayId() {
      return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
    }
    /**
     * <code>.id.EntityId relayId = 1;</code>
     */
    public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
      return getRelayId();
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 2;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (relayId_ != null) {
        output.writeMessage(1, getRelayId());
      }
      if (!address_.isEmpty()) {
        output.writeBytes(2, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (relayId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRelayId());
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.networknext.api.near.Near.NearResponseRelay)) {
        return super.equals(obj);
      }
      com.networknext.api.near.Near.NearResponseRelay other = (com.networknext.api.near.Near.NearResponseRelay) obj;

      boolean result = true;
      result = result && (hasRelayId() == other.hasRelayId());
      if (hasRelayId()) {
        result = result && getRelayId()
            .equals(other.getRelayId());
      }
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRelayId()) {
        hash = (37 * hash) + RELAYID_FIELD_NUMBER;
        hash = (53 * hash) + getRelayId().hashCode();
      }
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.networknext.api.near.Near.NearResponseRelay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.networknext.api.near.Near.NearResponseRelay prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code near.NearResponseRelay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:near.NearResponseRelay)
        com.networknext.api.near.Near.NearResponseRelayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networknext.api.near.Near.internal_static_near_NearResponseRelay_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networknext.api.near.Near.internal_static_near_NearResponseRelay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.networknext.api.near.Near.NearResponseRelay.class, com.networknext.api.near.Near.NearResponseRelay.Builder.class);
      }

      // Construct using com.networknext.api.near.Near.NearResponseRelay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (relayIdBuilder_ == null) {
          relayId_ = null;
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }
        address_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networknext.api.near.Near.internal_static_near_NearResponseRelay_descriptor;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponseRelay getDefaultInstanceForType() {
        return com.networknext.api.near.Near.NearResponseRelay.getDefaultInstance();
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponseRelay build() {
        com.networknext.api.near.Near.NearResponseRelay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.networknext.api.near.Near.NearResponseRelay buildPartial() {
        com.networknext.api.near.Near.NearResponseRelay result = new com.networknext.api.near.Near.NearResponseRelay(this);
        if (relayIdBuilder_ == null) {
          result.relayId_ = relayId_;
        } else {
          result.relayId_ = relayIdBuilder_.build();
        }
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networknext.api.near.Near.NearResponseRelay) {
          return mergeFrom((com.networknext.api.near.Near.NearResponseRelay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.networknext.api.near.Near.NearResponseRelay other) {
        if (other == com.networknext.api.near.Near.NearResponseRelay.getDefaultInstance()) return this;
        if (other.hasRelayId()) {
          mergeRelayId(other.getRelayId());
        }
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.networknext.api.near.Near.NearResponseRelay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.networknext.api.near.Near.NearResponseRelay) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.networknext.api.id.Id.EntityId relayId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> relayIdBuilder_;
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public boolean hasRelayId() {
        return relayIdBuilder_ != null || relayId_ != null;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityId getRelayId() {
        if (relayIdBuilder_ == null) {
          return relayId_ == null ? com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        } else {
          return relayIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder setRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relayId_ = value;
          onChanged();
        } else {
          relayIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder setRelayId(
          com.networknext.api.id.Id.EntityId.Builder builderForValue) {
        if (relayIdBuilder_ == null) {
          relayId_ = builderForValue.build();
          onChanged();
        } else {
          relayIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder mergeRelayId(com.networknext.api.id.Id.EntityId value) {
        if (relayIdBuilder_ == null) {
          if (relayId_ != null) {
            relayId_ =
              com.networknext.api.id.Id.EntityId.newBuilder(relayId_).mergeFrom(value).buildPartial();
          } else {
            relayId_ = value;
          }
          onChanged();
        } else {
          relayIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public Builder clearRelayId() {
        if (relayIdBuilder_ == null) {
          relayId_ = null;
          onChanged();
        } else {
          relayId_ = null;
          relayIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityId.Builder getRelayIdBuilder() {
        
        onChanged();
        return getRelayIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      public com.networknext.api.id.Id.EntityIdOrBuilder getRelayIdOrBuilder() {
        if (relayIdBuilder_ != null) {
          return relayIdBuilder_.getMessageOrBuilder();
        } else {
          return relayId_ == null ?
              com.networknext.api.id.Id.EntityId.getDefaultInstance() : relayId_;
        }
      }
      /**
       * <code>.id.EntityId relayId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder> 
          getRelayIdFieldBuilder() {
        if (relayIdBuilder_ == null) {
          relayIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.networknext.api.id.Id.EntityId, com.networknext.api.id.Id.EntityId.Builder, com.networknext.api.id.Id.EntityIdOrBuilder>(
                  getRelayId(),
                  getParentForChildren(),
                  isClean());
          relayId_ = null;
        }
        return relayIdBuilder_;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 2;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 2;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 2;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:near.NearResponseRelay)
    }

    // @@protoc_insertion_point(class_scope:near.NearResponseRelay)
    private static final com.networknext.api.near.Near.NearResponseRelay DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.networknext.api.near.Near.NearResponseRelay();
    }

    public static com.networknext.api.near.Near.NearResponseRelay getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NearResponseRelay>
        PARSER = new com.google.protobuf.AbstractParser<NearResponseRelay>() {
      @java.lang.Override
      public NearResponseRelay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NearResponseRelay(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NearResponseRelay> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NearResponseRelay> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.networknext.api.near.Near.NearResponseRelay getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_near_NearRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_near_NearRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_near_NearResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_near_NearResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_near_NearResponseRelay_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_near_NearResponseRelay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017near/near.proto\022\004near\032\013id/id.proto\"d\n\013" +
      "NearRequest\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitu" +
      "de\030\002 \001(\002\022\021\n\tmaxRelays\030\003 \001(\r\022\035\n\007exclude\030\004" +
      " \003(\0132\014.id.EntityId\"7\n\014NearResponse\022\'\n\006re" +
      "lays\030\001 \003(\0132\027.near.NearResponseRelay\"C\n\021N" +
      "earResponseRelay\022\035\n\007relayId\030\001 \001(\0132\014.id.E" +
      "ntityId\022\017\n\007address\030\002 \001(\0142>\n\013NearService\022" +
      "/\n\004Near\022\021.near.NearRequest\032\022.near.NearRe" +
      "sponse\"\000B \n\030com.networknext.api.nearZ\004ne" +
      "arb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.networknext.api.id.Id.getDescriptor(),
        }, assigner);
    internal_static_near_NearRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_near_NearRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_near_NearRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "MaxRelays", "Exclude", });
    internal_static_near_NearResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_near_NearResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_near_NearResponse_descriptor,
        new java.lang.String[] { "Relays", });
    internal_static_near_NearResponseRelay_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_near_NearResponseRelay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_near_NearResponseRelay_descriptor,
        new java.lang.String[] { "RelayId", "Address", });
    com.networknext.api.id.Id.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
