
CREATE DATABASE network_next;

\c network_next

CREATE TABLE customers (
  id integer generated by default as identity,
  live boolean not null default false,
  debug boolean not null default false,
  customer_name varchar not null,
  customer_code varchar not null,
  looker_seats integer not null default 0,
  tos_signer_email varchar null,
  tos_signer_first_name varchar null,
  tos_signer_last_name varchar null,
  tos_signed_timestamp varchar null,
  automatic_signin_domain varchar null,
  primary key (id),
  constraint customer_code_constraint unique(customer_code)
);

CREATE TABLE buyers (
  id integer generated by default as identity,
  short_name varchar,
  public_key_base64 varchar not null,
  customer_id integer not null,
  primary key (id),
  constraint fk_customer_id foreign key (customer_id) references customers(id)
);

CREATE TABLE sellers (
  id integer generated by default as identity,
  short_name varchar,
  customer_id integer,
  primary key (id),
  constraint fk_customer_id foreign key (customer_id) references customers(id),
  constraint seller_short_name unique(short_name)
);

CREATE TABLE route_shaders (
  id integer generated by default as identity,
  ab_test boolean not null,
  acceptable_latency integer not null,
  acceptable_packet_loss numeric not null,
  analysis_only boolean not null,
  bandwidth_envelope_down_kbps integer not null,
  bandwidth_envelope_up_kbps integer not null,
  disable_network_next boolean not null,
  latency_threshold integer not null,
  multipath boolean not null,
  reduce_latency boolean not null,
  reduce_packet_loss boolean not null,
  selection_percent integer not null,
  max_latency_tradeoff integer not null,
  max_rtt integer not null,
  route_switch_threshold integer not null,
  route_select_threshold integer not null,
  rtt_veto_default integer not null,
  rtt_veto_multipath integer not null,
  rtt_veto_packetloss integer not null,
  force_next boolean not null,
  buyer_id integer not null,
  primary key (id),
  constraint fk_buyer_id foreign key (buyer_id) references buyers(id)
);

CREATE TABLE datacenters (
  id integer generated by default as identity,
  display_name varchar not null unique,
  enabled boolean not null default true,
  latitude numeric not null,
  longitude numeric not null,
  seller_id integer not null,
  notes varchar,
  primary key (id),
  constraint fk_seller_id foreign key (seller_id) references sellers(id)
);

create table datacenter_maps (
  buyer_id integer not null,
  datacenter_id integer not null,
  enable_acceleration boolean not null default true,
  primary key (buyer_id, datacenter_id),
  constraint fk_buyer foreign key (buyer_id) references buyers(id),
  constraint fk_datacenter foreign key (datacenter_id) references datacenters(id)
);

CREATE TABLE relays (
  id integer generated by default as identity,
  display_name varchar not null,
  datacenter integer not null,
  public_ip inet not null,
  public_port integer not null default 40000,
  internal_ip inet,
  internal_port integer,
  ssh_ip varchar,
  ssh_port integer not null default 22,
  ssh_user varchar not null default 'root',
  public_key_base64 varchar not null,
  private_key_base64 varchar,
  mrc bigint not null default 0,
  port_speed integer not null default 1000,
  max_sessions integer not null default 0,
  notes varchar,
  primary key (id),
  constraint fk_datacenter foreign key (datacenter) references datacenters(id),
  constraint relay_name unique(display_name)
);
