
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS route_shaders CASCADE;
DROP TABLE IF EXISTS datacenters CASCADE;
DROP TABLE IF EXISTS datacenter_maps CASCADE;
DROP TABLE IF EXISTS relays CASCADE;

DROP DATABASE IF EXISTS nn;

DROP USER IF EXISTS admin;
DROP USER IF EXISTS operations;
DROP USER IF EXISTS engineering;
DROP USER IF EXISTS customer;
