
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS route_shaders CASCADE;
DROP TABLE IF EXISTS datacenters CASCADE;
DROP TABLE IF EXISTS relays CASCADE;
DROP TABLE IF EXISTS buyer_datacenter_settings CASCADE;
DROP TABLE IF EXISTS buyer_keypairs CASCADE;
DROP TABLE IF EXISTS relay_keypairs CASCADE;
