version: v1.0
name: Production Deploy
agent:
  machine:
    type: e1-standard-8
    os_image: ubuntu1804
global_job_config:
  prologue:
    commands:
      - sudo apt-get update && sudo apt-get -y install libsodium-dev libzmq3-dev
      - gcloud auth activate-service-account --key-file=/home/semaphore/gcp-service-account.json
      - gcloud auth configure-docker -q
      - checkout
      - sem-version go 1.13
      - make clean
blocks:
  - name: Build & Publish Artifacts
    dependencies: []
    task:
      jobs:
        - name: Server Backend
          commands:
            - make build-server-backend-artifacts-prod-esl
            - make publish-server-backend-artifacts-prod-esl
        - name: Bootstrap Script
          commands:
            - make publish-bootstrap-script-prod
      secrets:
        - name: google-cloud-platform-prod
