version: v1.0
name: Production Debug Deploy
agent:
  machine:
    type: e1-standard-8
    os_image: ubuntu1804
global_job_config:
  secrets:
    - name: sdk5-repo-access
  prologue:
    commands:
      - sudo apt-get update && sudo apt-get -y install libsodium-dev libzmq3-dev
      - gcloud auth activate-service-account --key-file=/home/semaphore/gcp-service-account.json
      - gcloud auth configure-docker -q
      - checkout
      - sem-version go 1.13
      - make clean
      - chmod 0600 ~/.ssh/id_rsa_semaphoreci_sdk5
      - ssh-add ~/.ssh/id_rsa_semaphoreci_sdk5
      - git submodule init
      - git submodule update
blocks:
  - name: Build & Publish Artifacts
    dependencies: []
    task:
      jobs:
        - name: Debug Server Backend
          commands:
            - make build-debug-server-backend-artifacts-prod-debug
            - make publish-debug-server-backend-artifacts-prod-debug
        - name: Debug Relay Backend
          commands:
            - make build-debug-relay-backend-artifacts-prod-debug
            - make publish-debug-relay-backend-artifacts-prod-debug
        - name: Debug Billing
          commands:
            - make build-debug-billing-artifacts-prod-debug
            - make publish-debug-billing-artifacts-prod-debug
        - name: Bootstrap Script
          commands:
            - make publish-bootstrap-script-prod-debug
      secrets:
        - name: google-cloud-platform-prod
