version: v1.0
name: Production Deploy
agent:
  machine:
    type: e1-standard-8
    os_image: ubuntu1804
global_job_config:
  secrets:
    - name: sdk4-repo-access
  prologue:
    commands:
      - sudo apt-get update && sudo apt-get -y install libsodium-dev libzmq3-dev
      - gcloud auth activate-service-account --key-file=/home/semaphore/gcp-service-account.json
      - gcloud auth configure-docker -q
      - checkout
      - sem-version go 1.13
      - make clean
      - chmod 0600 ~/.ssh/id_rsa_semaphoreci_sdk4
      - ssh-add ~/.ssh/id_rsa_semaphoreci_sdk4
      - git submodule init
      - git submodule update
blocks:
  - name: Build & Publish Artifacts
    dependencies: []
    task:
      jobs:
        - name: Billing
          commands:
            - make build-billing-artifacts-prod
            - make publish-billing-artifacts-prod
        - name: Analytics Pusher
          commands:
            - make build-analytics-pusher-artifacts-prod
            - make publish-analytics-pusher-artifacts-prod
        - name: Analytics
          commands:
            - make build-analytics-artifacts-prod
            - make publish-analytics-artifacts-prod
        - name: API
          commands:
            - make build-api-artifacts-prod
            - make publish-api-artifacts-prod
        - name: Vanity
          commands:
            - make build-vanity-artifacts-prod
            - make publish-vanity-artifacts-prod
        - name: Portal
          commands:
            - make build-portal-artifacts-prod
            - make publish-portal-artifacts-prod
        - name: Portal Cruncher
          commands:
            - make build-portal-cruncher-artifacts-prod
            - make publish-portal-cruncher-artifacts-prod
        - name: Relay Gateway
          commands:
            - make build-relay-gateway-artifacts-prod
            - make publish-relay-gateway-artifacts-prod
        - name: Relay Backend
          commands:
            - make build-relay-backend-artifacts-prod
            - make publish-relay-backend-artifacts-prod
        - name: Relay Frontend
          commands:
            - make build-relay-frontend-artifacts-prod
            - make publish-relay-frontend-artifacts-prod
        - name: Relay Forwarder
          commands:
            - make build-relay-forwarder-artifacts-prod
            - make publish-relay-forwarder-artifacts-prod
        - name: Server Backend
          commands:
            - make build-server-backend-artifacts-prod
            - make publish-server-backend-artifacts-prod
        - name: Debug Server Backend
          commands:
            - make build-debug-server-backend-artifacts-prod
            - make publish-debug-server-backend-artifacts-prod
        - name: Debug Relay Backend
          commands:
            - make build-debug-relay-backend-artifacts-prod
            - make publish-debug-relay-backend-artifacts-prod
        - name: Bootstrap Script
          commands:
            - make publish-bootstrap-script-prod
        - name: Ghost Army
          commands:
            - make build-ghost-army-artifacts-prod
            - make publish-ghost-army-artifacts-prod
            - make publish-ghost-army-bootstrap-script-prod
        - name: Relay Pusher
          commands:
            - make build-relay-pusher-artifacts-prod
            - make publish-relay-pusher-artifacts-prod
        - name: Pingdom
          commands:
            - make build-pingdom-artifacts-prod
            - make publish-pingdom-artifacts-prod
      secrets:
        - name: google-cloud-platform-prod
